"""
Django settings for stok_sistemi project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3$#t$2b!z3n)mxl0e(trox&b(2^rdjdeb@@gbd#e8cl6go2u+j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stokapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'stokapp.rbac_middleware.RbacMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'stokapp.middleware.HataLogMiddleware',  # Hata loglama middleware'i
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stok_sistemi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stokapp.context_processors.kritik_stok_bildirimi',
                'stokapp.context_processors.rbac_menus',
                'stokapp.context_processors.system_ai_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'stok_sistemi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# default: mevcut SQLite (değiştirilmedi).
# postgres: ikincil PostgreSQL bağlantısı — şifre ve isteğe bağlı host/port .env üzerinden.
# Yerel .env örneği: .env.example (TEKOS_POSTGRES_*)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('TEKOS_POSTGRES_DB', 'tekos_db'),
        'USER': os.environ.get('TEKOS_POSTGRES_USER', 'tekos_user'),
        'PASSWORD': os.environ.get('TEKOS_POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('TEKOS_POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('TEKOS_POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 0,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = '/admin/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'stokapp', 'static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# E-posta Ayarları
# Outlook SMTP Ayarları (turkticaret.net)
# Özel backend kullanıyoruz - SSL sertifika doğrulama sorunlarını çözmek için
EMAIL_BACKEND = 'stokapp.email_backend.CustomSMTPEmailBackend'
EMAIL_HOST = 'smtp.turkticaret.net'
EMAIL_PORT = 587  # TLS/STARTTLS için
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # TLS kullanıldığı için SSL False
EMAIL_HOST_USER = 'uretimplanlama@tekmarendustriyel.com'
EMAIL_HOST_PASSWORD = '*Bora0532'
DEFAULT_FROM_EMAIL = 'uretimplanlama@tekmarendustriyel.com'
SERVER_EMAIL = 'uretimplanlama@tekmarendustriyel.com'

# Not: Eğer 587 portu çalışmazsa, SSL için aşağıdaki ayarları kullanın:
# EMAIL_PORT = 465
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True

# IMAP Ayarları (.env)
IMAP_SERVER = os.getenv("IMAP_SERVER")
IMAP_PORT = int(os.getenv("IMAP_PORT", "993"))
MAIL_ACCOUNTS_JSON = os.getenv("MAIL_ACCOUNTS_JSON", "[]")
