# Generated by Django 5.2.7 on 2026-07-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformauditlog',
            new_name='core_platfo_company_731098_idx',
            old_name='core_platfo_company_0d9f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditlog',
            new_name='core_platfo_action_9e7139_idx',
            old_name='core_platfo_action_8c1e4b_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditlog',
            new_name='core_platfo_model_n_b447f5_idx',
            old_name='core_platfo_model_n_4a2c7d_idx',
        ),
    ]
