# Generated by Django 5.2.7 on 2026-07-22 08:29

import core.models.application
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _seed_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model("core", "LegalDocument")
    if LegalDocument.objects.exists():
        return
    LegalDocument.objects.create(
        doc_type="kvkk",
        version="1.0",
        title="KVKK Aydınlatma Metni",
        content=(
            "TEKOS platformu kapsamında kişisel verileriniz 6698 sayılı KVKK kapsamında "
            "işlenmektedir. Başvuru ve deneme sürecinde ad, soyad, e-posta, telefon ve firma "
            "bilgileriniz hesap oluşturma, iletişim ve hizmet sunumu amacıyla kullanılır."
        ),
        is_active=True,
    )
    LegalDocument.objects.create(
        doc_type="terms",
        version="1.0",
        title="Kullanım Koşulları",
        content=(
            "TEKOS yazılımını deneme ve kullanım süresince platform kurallarına uymayı, "
            "hesap bilgilerinizi gizli tutmayı ve yürürlükteki mevzuata uygun hareket etmeyi "
            "kabul edersiniz."
        ),
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_audit_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demo_seed_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('permission_change', 'Permission change'), ('settings_change', 'Settings change'), ('signup', 'Signup')], max_length=32),
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('kvkk', 'KVKK Aydınlatma Metni'), ('terms', 'Kullanım Koşulları')], db_index=True, max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SignupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('trial', 'Ücretsiz Deneme'), ('developer', 'Geliştirici Başvurusu')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('email_verification_pending', 'E-posta doğrulama bekliyor'), ('submitted', 'Gönderildi'), ('provisioning', 'Hesap oluşturuluyor'), ('active', 'Aktif'), ('review_pending', 'İnceleme bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('expired', 'Süresi doldu'), ('cancelled', 'İptal'), ('failed', 'Başarısız'), ('duplicate', 'Yinelenen'), ('converted', 'Müşteriye dönüştürüldü')], db_index=True, default='draft', max_length=32)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(blank=True, default='Türkiye', max_length=80)),
                ('company_size', models.CharField(blank=True, choices=[('1-5', '1–5'), ('6-10', '6–10'), ('11-25', '11–25'), ('26-50', '26–50'), ('51-100', '51–100'), ('101-250', '101–250'), ('250+', '250+')], default='', max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('metal', 'Metal / Makine'), ('otomotiv', 'Otomotiv'), ('elektronik', 'Elektronik'), ('gida', 'Gıda'), ('tekstil', 'Tekstil'), ('kimya', 'Kimya'), ('mobilya', 'Mobilya'), ('plastik', 'Plastik'), ('lojistik', 'Lojistik'), ('yazilim', 'Yazılım / Hizmet'), ('diger', 'Diğer')], default='', max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('username_preference', models.CharField(blank=True, default='', max_length=150)),
                ('trial_modules', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('utm_source', models.CharField(blank=True, default='', max_length=80)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=80)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('referrer_url', models.URLField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('language', models.CharField(blank=True, default='tr', max_length=16)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kvkk_accepted', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('commercial_communication_accepted', models.BooleanField(default=False)),
                ('legal_document_versions', models.JSONField(blank=True, default=dict)),
                ('developer_profile', models.JSONField(blank=True, default=dict)),
                ('provisioning_idempotency_key', models.CharField(blank=True, default='', max_length=64, null=True, unique=True)),
                ('failure_summary', models.CharField(blank=True, default='', max_length=500)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('trial_notification_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_signup_applications', to=settings.AUTH_USER_MODEL)),
                ('created_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_applications', to='core.company')),
                ('created_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_applications', to='core.subscription')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_applications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='core.signupapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.application.application_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.signupapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.signupapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signupapplication',
            index=models.Index(fields=['application_type', 'status'], name='core_signup_applica_40810b_idx'),
        ),
        migrations.AddIndex(
            model_name='signupapplication',
            index=models.Index(fields=['email', 'status'], name='core_signup_email_f0abf2_idx'),
        ),
        migrations.RunPython(_seed_legal_documents, migrations.RunPython.noop),
    ]
