# Generated by Django 5.2.7 on 2025-11-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('stok_tipi', models.CharField(choices=[('HAM_MADDE', 'Ham Madde'), ('YARI_MAMUL', 'Yarı Mamül'), ('URUN', 'Ürün')], default='HAM_MADDE', max_length=15)),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiyon', models.CharField(default='1.0', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adres', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=50, unique=True)),
                ('ad', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('birim', models.CharField(default='Adet', max_length=20)),
                ('barkod', models.CharField(blank=True, max_length=100)),
                ('alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alis_para_birimi', models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3)),
                ('mevcut_miktar', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('minimum_stok', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('guvenlik_stoku', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('uretim_suresi', models.IntegerField(default=0, help_text='Dakika cinsinden')),
                ('uretim_maliyeti', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.kategori')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.tedarikci')),
            ],
        ),
        migrations.CreateModel(
            name='ReceteDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('birim', models.CharField(max_length=20)),
                ('sira', models.IntegerField(default=0)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='stokapp.recete')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stokapp.stokitem')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='recete',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ana_urun', to='stokapp.stokitem'),
        ),
        migrations.CreateModel(
            name='UretimEmri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emir_no', models.CharField(max_length=50, unique=True)),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('durum', models.CharField(choices=[('PLANLANDI', 'Planlandı'), ('BASLADI', 'Üretim Başladı'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal Edildi')], default='PLANLANDI', max_length=15)),
                ('planlanan_baslama', models.DateTimeField()),
                ('planlanan_bitis', models.DateTimeField()),
                ('gerceklesen_baslama', models.DateTimeField(blank=True, null=True)),
                ('gerceklesen_bitis', models.DateTimeField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.recete')),
            ],
        ),
        migrations.CreateModel(
            name='UretimAsamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sira', models.IntegerField(default=0)),
                ('planlanan_sure', models.IntegerField(help_text='Dakika cinsinden')),
                ('gerceklesen_sure', models.IntegerField(blank=True, null=True)),
                ('baslama_zamani', models.DateTimeField(blank=True, null=True)),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(default='BEKLIYOR', max_length=20)),
                ('notlar', models.TextField(blank=True)),
                ('uretim_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asamalar', to='stokapp.uretimemri')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='StokHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('GIRIS', 'Stok Girişi'), ('CIKIS', 'Stok Çıkışı'), ('TRANSFER', 'Depo Transferi'), ('SAYIM', 'Sayım Düzeltmesi'), ('URETIM_GIRIS', 'Üretim Girişi'), ('URETIM_CIKIS', 'Üretim Çıkışı')], max_length=15)),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('birim', models.CharField(max_length=20)),
                ('referans_no', models.CharField(blank=True, max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('user', models.CharField(default='Sistem', max_length=100)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('onceki_stok', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sonraki_stok', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stokapp.stokitem')),
                ('uretim_emri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.uretimemri')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recete',
            unique_together={('urun', 'versiyon')},
        ),
    ]
