# Generated by Django 5.2.7 on 2025-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_kodu', models.CharField(max_length=50, unique=True)),
                ('unvan', models.CharField(max_length=200)),
                ('cari_tipi', models.CharField(choices=[('MUSTERI', 'Müşteri'), ('TEDARIKCI', 'Tedarikçi'), ('DIGER', 'Diğer')], default='MUSTERI', max_length=10)),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100)),
                ('vergi_no', models.CharField(blank=True, max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adres', models.TextField(blank=True)),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('risk_limiti', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aktif', models.BooleanField(default=True)),
                ('aciklama', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cari',
                'verbose_name_plural': 'Cariler',
                'ordering': ['unvan'],
            },
        ),
    ]
