# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0003_stokitem_onceki_stok_stokitem_sonraki_stok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='yetkili',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
