# Generated by Django 5.2.7 on 2025-11-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0004_add_yetkili_to_cari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='stokitem',
            name='acilis_miktari',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='arsivli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='stok_foto/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='satin_alma_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='satis_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='stok_takip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='tedarikci_kodu',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='urun_tipi',
            field=models.CharField(choices=[('SATINAL', 'Satın Alma'), ('URETIM', 'Üretim')], default='SATINAL', max_length=10),
        ),
        migrations.AddField(
            model_name='stokitem',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.depo'),
        ),
        migrations.CreateModel(
            name='EkDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='stok_ekleri/%Y/%m/%d/')),
                ('ad', models.CharField(blank=True, max_length=160, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_dosyalar', to='stokapp.stokitem')),
            ],
        ),
        migrations.CreateModel(
            name='Raf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raflar', to='stokapp.depo')),
            ],
            options={
                'unique_together': {('depo', 'ad')},
            },
        ),
        migrations.AddField(
            model_name='stokitem',
            name='raf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.raf'),
        ),
    ]
