# Generated by Django 5.2.7 on 2025-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0005_birim_depo_stokitem_acilis_miktari_stokitem_arsivli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stokitem',
            name='onceki_stok',
        ),
        migrations.RemoveField(
            model_name='stokitem',
            name='sonraki_stok',
        ),
        migrations.RemoveField(
            model_name='stokitem',
            name='tarih',
        ),
    ]
