# Generated by Django 5.2.7 on 2025-11-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0006_remove_stokitem_onceki_stok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_alis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('eski_satis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('eski_satin_alma_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('yeni_alis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('yeni_satis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('yeni_satin_alma_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('para_birimi', models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3)),
                ('degisen_alan', models.CharField(help_text='Hangi fiyat alanı değişti', max_length=30)),
                ('aciklama', models.TextField(blank=True)),
                ('user', models.CharField(default='Sistem', max_length=100)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiyat_gecmisi', to='stokapp.stokitem')),
            ],
            options={
                'verbose_name': 'Fiyat Geçmişi',
                'verbose_name_plural': 'Fiyat Geçmişleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
