# Generated by Django 5.2.7 on 2025-11-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0007_fiyatgecmisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokhareketi',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hareketler', to='stokapp.depo'),
        ),
        migrations.AddField(
            model_name='stokhareketi',
            name='raf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hareketler', to='stokapp.raf'),
        ),
    ]
