# Generated by Django 5.2.7 on 2025-11-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0008_stokhareketi_depo_stokhareketi_raf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaBirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text='Para birimi kodu (örn: TL, USD, EUR)', max_length=10, unique=True)),
                ('ad', models.CharField(help_text='Para birimi adı (örn: Türk Lirası)', max_length=100)),
                ('sembol', models.CharField(help_text='Para birimi sembolü (örn: ₺, $, €)', max_length=10)),
                ('aktif', models.BooleanField(default=True, help_text='Para birimi aktif mi?')),
            ],
            options={
                'verbose_name': 'Para Birimi',
                'verbose_name_plural': 'Para Birimleri',
                'ordering': ['kod'],
            },
        ),
    ]
