# Generated by Django 5.2.7 on 2025-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0009_parabirimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokitem',
            name='maximum_stok',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
