# Generated by Django 5.2.7 on 2025-11-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0010_stokitem_maximum_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenelAyarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_ismi', models.CharField(blank=True, default='', max_length=200, verbose_name='Firma İsmi')),
                ('telefon', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Posta')),
                ('varsayilan_satis_teslimat_suresi', models.IntegerField(default=15, help_text='Gün cinsinden', verbose_name='Varsayılan Satış Siparişi Teslimat Süresi')),
                ('varsayilan_satin_alma_teslimat_suresi', models.IntegerField(default=5, help_text='Gün cinsinden', verbose_name='Varsayılan Satın Alma Teslimat Süresi')),
                ('varsayilan_uretim_suresi', models.IntegerField(default=16, help_text='Gün cinsinden', verbose_name='Varsayılan Üretim Süresi')),
                ('satis_irsaliyesi_oneki', models.CharField(default='SO', max_length=20, verbose_name='Satış İrsaliyesi Öneki')),
                ('satin_alma_irsaliyesi_oneki', models.CharField(default='TSAT', max_length=20, verbose_name='Satın Alma İrsaliyesi Öneki')),
                ('is_emri_oneki', models.CharField(default='TWRK', max_length=20, verbose_name='İş Emri Öneki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_tanimli_satin_alma_lokasyonu', models.ForeignKey(blank=True, help_text='Varsayılan satın alma lokasyonu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satin_alma_lokasyonu', to='stokapp.depo', verbose_name='Ön Tanımlı Satın Alma Lokasyonu')),
                ('on_tanimli_satis_lokasyonu', models.ForeignKey(blank=True, help_text='Varsayılan satış lokasyonu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satis_lokasyonu', to='stokapp.depo', verbose_name='Ön Tanımlı Satış Lokasyonu')),
                ('on_tanimli_uretim_lokasyonu', models.ForeignKey(blank=True, help_text='Varsayılan üretim lokasyonu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_lokasyonu', to='stokapp.depo', verbose_name='Ön Tanımlı Üretim Lokasyonu')),
                ('para_birimi', models.ForeignKey(blank=True, help_text='Varsayılan para birimi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.parabirimi', verbose_name='Para Birimi')),
            ],
            options={
                'verbose_name': 'Genel Ayarlar',
                'verbose_name_plural': 'Genel Ayarlar',
            },
        ),
    ]
