# Generated by Django 5.2.7 on 2025-11-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0012_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True, verbose_name='Operasyon Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operasyon',
                'verbose_name_plural': 'Operasyonlar',
                'ordering': ['sira', 'ad'],
            },
        ),
    ]
