# Generated by Django 5.2.7 on 2025-11-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0013_operasyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True, verbose_name='İstasyon Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='istasyonlar/', verbose_name='İstasyon Fotoğrafı')),
                ('maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maliyet (TRY)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İstasyon',
                'verbose_name_plural': 'İstasyonlar',
                'ordering': ['sira', 'ad'],
            },
        ),
    ]
