# Generated by Django 5.2.7 on 2025-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0014_istasyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varlik_adi', models.CharField(max_length=200, verbose_name='Varlık Adı')),
                ('varlik_kimlik_no', models.CharField(blank=True, max_length=100, verbose_name='Varlık Kimlik Numarası')),
                ('varlik_aciklama', models.TextField(blank=True, verbose_name='Varlık Açıklaması')),
                ('varlik_turu', models.CharField(choices=[('KISISEL', 'Kişisel'), ('SIRKET', 'Şirket')], default='SIRKET', max_length=10, verbose_name='Varlık Türü')),
                ('police_no', models.CharField(max_length=100, unique=True, verbose_name='Poliçe Numarası')),
                ('police_baslangic_tarihi', models.DateField(verbose_name='Poliçe Başlangıç Tarihi')),
                ('police_bitis_tarihi', models.DateField(verbose_name='Poliçe Bitiş Tarihi')),
                ('police_duzenleyen_firma', models.CharField(max_length=200, verbose_name='Poliçeyi Düzenleyen Firma')),
                ('police_prim_bedeli', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Poliçe Prim Bedeli')),
                ('odeme_hesap_kart', models.CharField(blank=True, max_length=200, verbose_name='Ödemenin Yapıldığı Hesap/Kart Bilgisi')),
                ('police_dosyasi', models.FileField(blank=True, null=True, upload_to='sigortalar/', verbose_name='Poliçe Dosyası (PDF)')),
                ('arsivlendi', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sigorta',
                'verbose_name_plural': 'Sigortalar',
                'ordering': ['-police_bitis_tarihi', 'varlik_adi'],
            },
        ),
    ]
