# Generated by Django 5.2.7 on 2025-11-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0015_sigorta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='AvansOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Ödeme Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Avans Tutarı (TRY)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avans_odemeler', to='stokapp.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Avans Ödeme',
                'verbose_name_plural': 'Avans Ödemeleri',
                'ordering': ['-tarih', 'personel'],
            },
        ),
        migrations.CreateModel(
            name='GunlukCalisma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Çalışma Tarihi')),
                ('calisma_suresi', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Çalışma Süresi (Saat)')),
                ('saat_ucreti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saat Ücreti (TRY)')),
                ('odenecek_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ödenecek Tutar (TRY)')),
                ('odeme_durumu', models.CharField(choices=[('ODENMEDI', 'Ödenmedi'), ('KISMI', 'Kısmi Ödendi'), ('ODENDI', 'Ödendi')], default='ODENMEDI', max_length=10, verbose_name='Ödeme Durumu')),
                ('odeme_sekli', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('HAVALE', 'Havale/EFT'), ('KREDI_KARTI', 'Kredi Kartı'), ('BANKA_KARTI', 'Banka Kartı'), ('DIGER', 'Diğer')], max_length=15, verbose_name='Ödeme Şekli')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ödenen Tutar (TRY)')),
                ('kalan_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kalan Bakiye (TRY)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_calismalar', to='stokapp.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Günlük Çalışma',
                'verbose_name_plural': 'Günlük Çalışmalar',
                'ordering': ['-tarih', 'personel'],
                'unique_together': {('personel', 'tarih')},
            },
        ),
    ]
