# Generated by Django 5.2.7 on 2025-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0016_personel_avansodeme_gunlukcalisma'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='adres',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='personel',
            name='ana_adi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ana Adı'),
        ),
        migrations.AddField(
            model_name='personel',
            name='baba_adi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Baba Adı'),
        ),
        migrations.AddField(
            model_name='personel',
            name='birim',
            field=models.CharField(blank=True, max_length=100, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='personel',
            name='bordro_islem',
            field=models.BooleanField(default=False, verbose_name='Bordro İşlem'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cilt_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cilt No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('ERKEK', 'Erkek'), ('KADIN', 'Kadın')], max_length=10, verbose_name='Cinsiyeti'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cuzdan_kayit_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cüzdan Kayıt No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cuzdan_seri_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cüzdan Seri No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cuzdan_verilis_nedeni',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cüzdan Veriliş Nedeni'),
        ),
        migrations.AddField(
            model_name='personel',
            name='cuzdan_verilis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Cüzdan Veriliş Tarihi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doğum Yeri'),
        ),
        migrations.AddField(
            model_name='personel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='personel',
            name='firma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='personel',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='personel/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='personel',
            name='gorev',
            field=models.CharField(blank=True, max_length=100, verbose_name='Görevi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='ilce',
            field=models.CharField(blank=True, max_length=100, verbose_name='İlçesi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='kan_grubu',
            field=models.CharField(blank=True, choices=[('A_RH_POS', 'A Rh +'), ('A_RH_NEG', 'A Rh -'), ('B_RH_POS', 'B Rh +'), ('B_RH_NEG', 'B Rh -'), ('AB_RH_POS', 'AB Rh +'), ('AB_RH_NEG', 'AB Rh -'), ('O_RH_POS', '0 Rh +'), ('O_RH_NEG', '0 Rh -')], max_length=10, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='personel',
            name='kutu_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kütük No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='mahalle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mahalle'),
        ),
        migrations.AddField(
            model_name='personel',
            name='medeni_hali',
            field=models.CharField(blank=True, choices=[('BEKAR', 'Bekar'), ('EVLI', 'Evli'), ('DUL', 'Dul'), ('BOSANMIS', 'Boşanmış')], max_length=15, verbose_name='Medeni Hali'),
        ),
        migrations.AddField(
            model_name='personel',
            name='onceki_soyadi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Önceki Soyadı'),
        ),
        migrations.AddField(
            model_name='personel',
            name='ozel_kod',
            field=models.CharField(blank=True, max_length=50, verbose_name='Özel Kod'),
        ),
        migrations.AddField(
            model_name='personel',
            name='pdks_takip',
            field=models.BooleanField(default=False, verbose_name='PDKS Takip'),
        ),
        migrations.AddField(
            model_name='personel',
            name='personel_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Personel No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='posta_kodu',
            field=models.CharField(blank=True, max_length=10, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='personel',
            name='saatlik_ucret',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saatlik Ücret (TRY)'),
        ),
        migrations.AddField(
            model_name='personel',
            name='sayfa_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sayfa No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='sehir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='personel',
            name='sicil_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sicil No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='sinif',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sınıf'),
        ),
        migrations.AddField(
            model_name='personel',
            name='takip_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Takip No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TC Kimlik No'),
        ),
        migrations.AddField(
            model_name='personel',
            name='ulke',
            field=models.CharField(blank=True, default='Türkiye', max_length=100, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='personel',
            name='unvan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ünvanı'),
        ),
    ]
