# Generated by Django 5.2.7 on 2025-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0017_personel_adres_personel_ana_adi_personel_baba_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avansodeme',
            name='odeme_sekli',
            field=models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('HAVALE', 'Havale/EFT'), ('KREDI_KARTI', 'Kredi Kartı'), ('BANKA_KARTI', 'Banka Kartı'), ('DIGER', 'Diğer')], max_length=15, verbose_name='Ödeme Şekli'),
        ),
    ]
