# Generated by Django 5.2.7 on 2025-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0018_avansodeme_odeme_sekli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_numarasi', models.CharField(max_length=50, unique=True, verbose_name='Sipariş Numarası')),
                ('musteri', models.CharField(max_length=200, verbose_name='Müşteri')),
                ('etiketler', models.CharField(blank=True, max_length=200, verbose_name='Etiketler')),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('para_birimi', models.CharField(default='USD', max_length=3, verbose_name='Para Birimi')),
                ('olusturulma_tarihi', models.DateField(verbose_name='Oluşturulma Tarihi')),
                ('tamamlanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('stok_durumu', models.CharField(choices=[('STOKTA_VAR', 'Stokta Var'), ('STOKTA_YOK', 'Stokta Yok'), ('KISMI_STOK', 'Kısmi Stok')], default='STOKTA_VAR', max_length=20, verbose_name='Stok Durumu')),
                ('hammadde_durumu', models.CharField(choices=[('STOKTA_VAR', 'Stokta Var'), ('STOKTA_YOK', 'Stokta Yok'), ('KISMI_STOK', 'Kısmi Stok')], default='STOKTA_VAR', max_length=20, verbose_name='Hammadde Durumu')),
                ('uretim_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Üretim Durumu')),
                ('teslimat_durumu', models.CharField(choices=[('HAZIRLANIYOR', 'Hazırlanıyor'), ('KARGOYA_VERILDI', 'Kargoya Verildi'), ('TESLIM_EDILDI', 'Teslim Edildi')], default='HAZIRLANIYOR', max_length=20, verbose_name='Teslimat Durumu')),
                ('fatura_durumu', models.CharField(choices=[('FATURALANMADI', 'Faturalanmadı'), ('FATURALANDI', 'Faturalandı'), ('KISMI_FATURA', 'Kısmi Fatura')], default='FATURALANMADI', max_length=20, verbose_name='Fatura Durumu')),
                ('siparis_durumu', models.CharField(choices=[('ONAY_BEKLIYOR', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('TESLIM_EDILDI', 'Teslim Edildi')], default='ONAY_BEKLIYOR', max_length=20, verbose_name='Sipariş Durumu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
