# Generated by Django 5.2.7 on 2025-11-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0019_siparis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('indirim_yuzdesi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İndirim (%)')),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stokapp.siparis', verbose_name='Sipariş')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'ordering': ['id'],
            },
        ),
    ]
