# Generated by Django 5.2.7 on 2025-11-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0021_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='musteri_adi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Müşteri Adı (Manuel)'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.musteri', verbose_name='Müşteri'),
        ),
    ]
