# Generated by Django 5.2.7 on 2025-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0022_siparis_musteri_adi_alter_siparis_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokitem',
            name='satis_para_birimi',
            field=models.CharField(blank=True, choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3, verbose_name='Satış Para Birimi'),
        ),
    ]
