# Generated by Django 5.2.7 on 2025-11-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0023_stokitem_satis_para_birimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satinalma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satinalma_numarasi', models.CharField(max_length=50, unique=True, verbose_name='Satın Alma Numarası')),
                ('tedarikci_adi', models.CharField(blank=True, max_length=200, verbose_name='Tedarikçi Adı (Manuel)')),
                ('etiketler', models.CharField(blank=True, max_length=200, verbose_name='Etiketler')),
                ('toplam', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('olusturulma_tarihi', models.DateField(verbose_name='Oluşturulma Tarihi')),
                ('tamamlanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Tamamlanması Beklenen Tarih')),
                ('teslim_durumu', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('KISMI_TESLIM', 'Kısmi Teslim'), ('TESLIM_ALINDI', 'Teslim Alındı')], default='BEKLIYOR', max_length=20, verbose_name='Teslim Alındı')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lokasyon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.depo', verbose_name='Lokasyon')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın Alma',
                'verbose_name_plural': 'Satın Almalar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatinalmaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyatı')),
                ('vergi_yuzdesi', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Vergi (%)')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Fiyat')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satinalma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stokapp.satinalma', verbose_name='Satın Alma')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Stok')),
            ],
            options={
                'verbose_name': 'Satın Alma Kalemi',
                'verbose_name_plural': 'Satın Alma Kalemleri',
                'ordering': ['id'],
            },
        ),
    ]
