# Generated by Django 5.2.7 on 2025-11-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0024_satinalma_satinalmakalemi'),
    ]

    operations = [
        migrations.CreateModel(
            name='YazdirmaSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('TEKLIF_TALEBI', 'Teklif Talebi Formu'), ('SIPARIS', 'Sipariş Formu'), ('MALZEME_LISTESI', 'Malzeme Listesi Formu'), ('IS_EMRI', 'İş Emri Formu'), ('BARKOD', 'Barkod Baskısı')], max_length=20, unique=True, verbose_name='Şablon Tipi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('logo_goster', models.BooleanField(default=True, verbose_name='Logo Göster')),
                ('logo_yolu', models.ImageField(blank=True, null=True, upload_to='sablon_logolar/%Y/%m/%d/', verbose_name='Logo Dosyası')),
                ('logo_pozisyon', models.CharField(choices=[('SOL', 'Sol'), ('SAG', 'Sağ'), ('ORTA', 'Orta')], default='SOL', max_length=20, verbose_name='Logo Pozisyonu')),
                ('logo_genislik', models.IntegerField(default=150, verbose_name='Logo Genişliği (px)')),
                ('logo_yukseklik', models.IntegerField(default=80, verbose_name='Logo Yüksekliği (px)')),
                ('baslik_metni', models.CharField(blank=True, default='', max_length=200, verbose_name='Başlık Metni')),
                ('baslik_font_boyutu', models.IntegerField(default=24, verbose_name='Başlık Font Boyutu')),
                ('baslik_font_rengi', models.CharField(default='#000000', max_length=7, verbose_name='Başlık Font Rengi')),
                ('baslik_kalin', models.BooleanField(default=True, verbose_name='Başlık Kalın')),
                ('baslik_pozisyon', models.CharField(choices=[('SOL', 'Sol'), ('SAG', 'Sağ'), ('ORTA', 'Orta')], default='ORTA', max_length=20, verbose_name='Başlık Pozisyonu')),
                ('tarih_goster', models.BooleanField(default=True, verbose_name='Tarih Göster')),
                ('tarih_format', models.CharField(default='%d.%m.%Y', max_length=50, verbose_name='Tarih Formatı')),
                ('tarih_pozisyon', models.CharField(choices=[('SOL', 'Sol'), ('SAG', 'Sağ'), ('ORTA', 'Orta')], default='SAG', max_length=20, verbose_name='Tarih Pozisyonu')),
                ('firma_adi', models.CharField(blank=True, max_length=200, verbose_name='Firma Adı')),
                ('firma_adres', models.TextField(blank=True, verbose_name='Firma Adres')),
                ('firma_telefon', models.CharField(blank=True, max_length=50, verbose_name='Firma Telefon')),
                ('firma_email', models.CharField(blank=True, max_length=100, verbose_name='Firma E-posta')),
                ('firma_vergi_no', models.CharField(blank=True, max_length=50, verbose_name='Vergi No')),
                ('alt_bilgi_goster', models.BooleanField(default=True, verbose_name='Alt Bilgi Göster')),
                ('alt_bilgi_metni', models.TextField(blank=True, verbose_name='Alt Bilgi Metni')),
                ('sayfa_kenar_bosluk', models.IntegerField(default=20, verbose_name='Kenar Boşluğu (mm)')),
                ('font_ailesi', models.CharField(default='Arial', max_length=50, verbose_name='Font Ailesi')),
                ('varsayilan_font_boyutu', models.IntegerField(default=12, verbose_name='Varsayılan Font Boyutu')),
                ('ozel_css', models.TextField(blank=True, verbose_name='Özel CSS')),
                ('ozel_html', models.TextField(blank=True, verbose_name='Özel HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yazdırma Şablonu',
                'verbose_name_plural': 'Yazdırma Şablonları',
                'ordering': ['tip'],
            },
        ),
    ]
