# Generated by Django 5.2.7 on 2025-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0025_yazdirmasablonu'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazdirmasablonu',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='yazdirmasablonu',
            name='api_kullan',
            field=models.BooleanField(default=False, verbose_name='API ile Düzenle'),
        ),
        migrations.AddField(
            model_name='yazdirmasablonu',
            name='editor_url',
            field=models.URLField(blank=True, verbose_name='Editor URL'),
        ),
        migrations.AddField(
            model_name='yazdirmasablonu',
            name='template_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Template Data (JSON)'),
        ),
        migrations.AddField(
            model_name='yazdirmasablonu',
            name='template_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Template ID'),
        ),
    ]
