# Generated by Django 5.2.7 on 2025-11-23 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0026_yazdirmasablonu_api_key_yazdirmasablonu_api_kullan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteOperasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maliyet (TRY/saat)')),
                ('sure_dakika', models.IntegerField(default=0, verbose_name='Süre (Dakika)')),
                ('toplam_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Maliyet (TRY)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bagimliliklar', models.ManyToManyField(blank=True, related_name='bagimli_operasyonlar', to='stokapp.receteoperasyon', verbose_name='Bağımlılıklar')),
                ('istasyon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.istasyon', verbose_name='İstasyon')),
                ('operasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.operasyon', verbose_name='Operasyon')),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operasyonlar', to='stokapp.recete')),
            ],
            options={
                'verbose_name': 'Reçete Operasyonu',
                'verbose_name_plural': 'Reçete Operasyonları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
