# Generated by Django 5.2.7 on 2025-11-26 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0027_receteoperasyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimStandarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Standart Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Standart Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('pdf_dosya', models.FileField(upload_to='uretim_standartlari/%Y/%m/%d/', verbose_name='PDF Dosyası')),
                ('olusturma_tarihi', models.DateField(verbose_name='İlk Oluşturma Tarihi')),
                ('revizyon_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Revizyon Tarihi')),
                ('revizyon_aciklama', models.TextField(blank=True, verbose_name='Revizyon Açıklaması')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Üretim Standartı',
                'verbose_name_plural': 'Üretim Standartları',
                'ordering': ['sira', 'kod'],
            },
        ),
        migrations.CreateModel(
            name='UretimStandartiArsiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_dosya', models.FileField(upload_to='uretim_standartlari/arsiv/%Y/%m/%d/', verbose_name='PDF Dosyası')),
                ('revizyon_tarihi', models.DateField(verbose_name='Revizyon Tarihi')),
                ('revizyon_aciklama', models.TextField(blank=True, verbose_name='Revizyon Açıklaması')),
                ('arsiv_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Arşivlenme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsivlenmis_versiyonlar', to='stokapp.uretimstandarti', verbose_name='Standart')),
            ],
            options={
                'verbose_name': 'Arşivlenmiş Standart Versiyonu',
                'verbose_name_plural': 'Arşivlenmiş Standart Versiyonları',
                'ordering': ['-revizyon_tarihi', '-arsiv_tarihi'],
            },
        ),
    ]
