# Generated by Django 5.2.7 on 2025-11-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0028_uretimstandarti_uretimstandartiarsiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='receteoperasyon',
            name='uretim_standarti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.uretimstandarti', verbose_name='Üretim Standartı'),
        ),
    ]
