# Generated by Django 5.2.7 on 2025-11-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0029_receteoperasyon_uretim_standarti'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalma',
            name='arsivlendi',
            field=models.BooleanField(default=False, verbose_name='Arşivlendi'),
        ),
        migrations.AddField(
            model_name='satinalmakalemi',
            name='teslim_alinan_miktar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Teslim Alınan Miktar'),
        ),
    ]
