# Generated by Django 5.2.7 on 2025-11-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0030_satinalma_arsivlendi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokitem',
            name='teknik_resim',
            field=models.FileField(blank=True, null=True, upload_to='stok_teknik_resim/%Y/%m/%d/', verbose_name='Teknik Resim (DXF/DWG)'),
        ),
    ]
