# Generated by Django 5.2.7 on 2025-11-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0031_stokitem_teknik_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalmakalemi',
            name='teknik_resim_guncellenmis',
            field=models.FileField(blank=True, null=True, upload_to='satinalma_teknik_resim/%Y/%m/%d/', verbose_name='Güncellenmiş Teknik Resim'),
        ),
    ]
