# Generated by Django 5.2.7 on 2025-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0032_satinalmakalemi_teknik_resim_guncellenmis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkalaSuiteEntegrasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('password', models.CharField(help_text='Skala Suite giriş şifresi', max_length=255, verbose_name='Şifre')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('son_stok_senkronizasyon', models.DateTimeField(blank=True, null=True, verbose_name='Son Stok Senkronizasyonu')),
                ('son_cari_senkronizasyon', models.DateTimeField(blank=True, null=True, verbose_name='Son Cari Senkronizasyonu')),
                ('son_recete_senkronizasyon', models.DateTimeField(blank=True, null=True, verbose_name='Son Reçete Senkronizasyonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skala Suite Entegrasyon',
                'verbose_name_plural': 'Skala Suite Entegrasyon Ayarları',
            },
        ),
    ]
