# Generated by Django 5.2.7 on 2025-11-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0033_skalasuiteentegrasyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('arac_tipi', models.CharField(choices=[('BINEK', 'Binek Araç'), ('TICARI', 'Ticari Araç'), ('MOTOSIKLET', 'Motosiklet'), ('DIGER', 'Diğer')], default='BINEK', max_length=20, verbose_name='Araç Tipi')),
                ('renk', models.CharField(blank=True, max_length=50, verbose_name='Renk')),
                ('sasi_no', models.CharField(blank=True, max_length=100, verbose_name='Şasi No')),
                ('motor_no', models.CharField(blank=True, max_length=100, verbose_name='Motor No')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='arac_foto/%Y/%m/%d/', verbose_name='Araç Fotoğrafı')),
                ('ruhsat_pdf', models.FileField(blank=True, null=True, upload_to='arac_ruhsat/%Y/%m/%d/', verbose_name='Ruhsat PDF')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'ordering': ['plaka'],
            },
        ),
        migrations.CreateModel(
            name='AracBelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_turu', models.CharField(choices=[('TUVTURK', 'TÜVTÜRK Muayene'), ('EGZOZ', 'Egzoz Emisyon'), ('TRAFIK_SIGORTA', 'Zorunlu Trafik Sigortası'), ('KASKO', 'Kasko'), ('MTV', 'MTV Ödeme'), ('SRC', 'SRC Belgesi'), ('PSIKOTEKNIK', 'Psikoteknik Belgesi'), ('K_BELGESI', 'K Belgesi'), ('SERVIS', 'Servis Formu'), ('HASAR', 'Hasar Tutanağı')], max_length=20, verbose_name='Belge Türü')),
                ('gecerlilik_baslangic', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Başlangıç Tarihi')),
                ('gecerlilik_bitis', models.DateField(verbose_name='Geçerlilik Bitiş Tarihi')),
                ('belge_pdf', models.FileField(blank=True, null=True, upload_to='arac_belgeler/%Y/%m/%d/', verbose_name='Belge PDF')),
                ('hasar_foto', models.ImageField(blank=True, help_text='Sadece hasar belgesi için', null=True, upload_to='arac_hasar/%Y/%m/%d/', verbose_name='Hasar Fotoğrafı')),
                ('belge_no', models.CharField(blank=True, max_length=100, verbose_name='Belge No')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belgeler', to='stokapp.arac', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Araç Belgesi',
                'verbose_name_plural': 'Araç Belgeleri',
                'ordering': ['-gecerlilik_bitis', 'arac'],
            },
        ),
    ]
