# Generated by Django 5.2.7 on 2025-11-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0034_arac_aracbelgesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankaHesabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_adi', models.CharField(max_length=200, verbose_name='Hesap Adı')),
                ('banka_adi', models.CharField(max_length=200, verbose_name='Banka Adı')),
                ('iban', models.CharField(help_text='TR ile başlayan 26 haneli IBAN', max_length=34, verbose_name='IBAN Numarası')),
                ('hesap_tipi', models.CharField(choices=[('SAHSI', 'Şahsi'), ('TICARI', 'Ticari')], default='TICARI', max_length=10, verbose_name='Hesap Tipi')),
                ('hesap_sahibi', models.CharField(blank=True, max_length=200, verbose_name='Hesap Sahibi')),
                ('sube_kodu', models.CharField(blank=True, max_length=20, verbose_name='Şube Kodu')),
                ('hesap_no', models.CharField(blank=True, max_length=50, verbose_name='Hesap Numarası')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='banka_hesaplari/%Y/%m/%d/', verbose_name='Fotoğraf')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banka Hesabı',
                'verbose_name_plural': 'Banka Hesapları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KrediKarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_adi', models.CharField(max_length=200, verbose_name='Kart Adı')),
                ('kart_numarasi', models.CharField(help_text='16 haneli kart numarası (son 4 hanesi görünebilir)', max_length=19, verbose_name='Kart Numarası')),
                ('son_kullanim_tarihi', models.CharField(help_text='MM/YY formatında', max_length=5, verbose_name='Son Kullanma Tarihi')),
                ('cvv', models.CharField(help_text='3 veya 4 haneli güvenlik kodu', max_length=4, verbose_name='CVV Kodu')),
                ('kart_sahibi', models.CharField(blank=True, max_length=200, verbose_name='Kart Sahibi')),
                ('banka_adi', models.CharField(blank=True, max_length=200, verbose_name='Banka Adı')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='kredi_kartlari/%Y/%m/%d/', verbose_name='Fotoğraf')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kredi Kartı',
                'verbose_name_plural': 'Kredi Kartları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AylikOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_aciklamasi', models.CharField(max_length=500, verbose_name='Ödeme Açıklaması')),
                ('odeme_sekli', models.CharField(choices=[('HAVALE_EFT', 'Havale/EFT'), ('KREDI_KARTI', 'Kredi Kartı'), ('BANKA_HESABI', 'Banka Hesabı')], max_length=20, verbose_name='Ödeme Şekli')),
                ('kayit_tarihi', models.DateField(verbose_name='Kayıt Tarihi')),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('tekrar_eden', models.BooleanField(default=False, help_text='Bu ödeme her ay tekrarlanıyor mu?', verbose_name='Tekrar Eden Ödeme')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('odeme_durumu', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ODENDI', 'Ödendi'), ('GECIKMIS', 'Gecikmiş')], default='BEKLEMEDE', max_length=20, verbose_name='Ödeme Durumu')),
                ('odeme_yapildi_tarih', models.DateField(blank=True, null=True, verbose_name='Ödeme Yapıldı Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banka_hesabi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aylik_odemeler', to='stokapp.bankahesabi', verbose_name='Banka Hesabı')),
                ('kredi_karti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aylik_odemeler', to='stokapp.kredikarti', verbose_name='Kredi Kartı')),
            ],
            options={
                'verbose_name': 'Aylık Ödeme',
                'verbose_name_plural': 'Aylık Ödemeler',
                'ordering': ['-odeme_tarihi', '-kayit_tarihi'],
            },
        ),
    ]
