# Generated by Django 5.2.7 on 2025-11-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0035_bankahesabi_kredikarti_aylikodeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aylikodeme',
            name='para_birimi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aylik_odemeler', to='stokapp.parabirimi', verbose_name='Para Birimi'),
        ),
    ]
