# Generated by Django 5.2.7 on 2025-12-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0036_aylikodeme_para_birimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiparisMaliyeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maliyet_tipi', models.CharField(choices=[('MALZEME', 'Malzeme'), ('OPERASYON', 'Operasyon')], max_length=20, verbose_name='Maliyet Tipi')),
                ('aciklama', models.CharField(max_length=500, verbose_name='Açıklama')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat')),
                ('toplam', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('birim', models.CharField(default='Adet', max_length=20, verbose_name='Birim')),
                ('kayit_tarihi', models.DateField(verbose_name='Kayıt Tarihi')),
                ('aciklama_detay', models.TextField(blank=True, verbose_name='Detay Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maliyetler', to='stokapp.siparis', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sipariş Maliyeti',
                'verbose_name_plural': 'Sipariş Maliyetleri',
                'ordering': ['maliyet_tipi', 'kayit_tarihi', 'id'],
            },
        ),
    ]
