# Generated by Django 5.2.7 on 2025-12-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0037_siparismaliyeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalmakalemi',
            name='tedarikci_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tedarikçiden gelen teklif fiyatı', max_digits=10, null=True, verbose_name='Tedarikçi Fiyatı'),
        ),
        migrations.AddField(
            model_name='satinalmakalemi',
            name='teslim_suresi',
            field=models.IntegerField(blank=True, help_text='Tedarikçiden gelen teslim süresi', null=True, verbose_name='Teslim Süresi (Gün)'),
        ),
    ]
