# Generated by Django 5.2.7 on 2025-12-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0038_satinalmakalemi_tedarikci_fiyat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteTalimat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra Numarası')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talimatlar', to='stokapp.recete')),
            ],
            options={
                'verbose_name': 'Reçete Talimatı',
                'verbose_name_plural': 'Reçete Talimatları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceteTalimatDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='recete_talimat_dosyalari/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(blank=True, max_length=255, verbose_name='Dosya Adı')),
                ('dosya_tipi', models.CharField(blank=True, max_length=50, verbose_name='Dosya Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Dosyası',
                'verbose_name_plural': 'Talimat Dosyaları',
            },
        ),
        migrations.CreateModel(
            name='ReceteTalimatEkipman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ekipman Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekipmanlar', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Ekipman',
                'verbose_name_plural': 'Talimat Ekipmanları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceteTalimatOlcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_deger', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Nominal Değer')),
                ('birim', models.CharField(blank=True, max_length=20, verbose_name='Birim')),
                ('min_deger', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Min Değer')),
                ('max_deger', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Değer')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olculer', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Ölçü',
                'verbose_name_plural': 'Talimat Ölçüleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceteTalimatProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_adi', models.CharField(max_length=200, verbose_name='Program Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programlar', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Program',
                'verbose_name_plural': 'Talimat Programları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
