# Generated by Django 5.2.7 on 2025-12-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0039_recetetalimat_recetetalimatdosya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetetalimatdosya',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Örn: İşlem Öncesi Görsel, Montaj Şeması', max_length=200, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='recetetalimatolcu',
            name='aciklama',
            field=models.CharField(blank=True, help_text='Örn: En, Boy, Kalınlık', max_length=200, verbose_name='Açıklama'),
        ),
    ]
