# Generated by Django 5.2.7 on 2025-12-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0040_recetetalimatdosya_aciklama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipman_numarasi', models.CharField(max_length=50, unique=True, verbose_name='Ekipman Numarası')),
                ('ad', models.CharField(max_length=200, verbose_name='Ekipman Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='ekipmanlar/', verbose_name='Ekipman Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ekipman',
                'verbose_name_plural': 'Ekipmanlar',
                'ordering': ['sira', 'ekipman_numarasi'],
            },
        ),
        migrations.CreateModel(
            name='Fikstur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fikstur_numarasi', models.CharField(max_length=50, unique=True, verbose_name='Fikstür Numarası')),
                ('ad', models.CharField(max_length=200, verbose_name='Fikstür Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Fikstür Açıklaması')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='fiksturler/', verbose_name='Fikstür Fotoğrafı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fikstür',
                'verbose_name_plural': 'Fikstürler',
                'ordering': ['sira', 'fikstur_numarasi'],
            },
        ),
        migrations.RemoveField(
            model_name='recetetalimatekipman',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='recetetalimatekipman',
            name='ad',
        ),
        migrations.AddField(
            model_name='recetetalimatekipman',
            name='ekipman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.ekipman', verbose_name='Ekipman'),
        ),
        migrations.CreateModel(
            name='ReceteTalimatFikstur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('fikstur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.fikstur', verbose_name='Fikstür')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiksturler', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Fikstür',
                'verbose_name_plural': 'Talimat Fikstürleri',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
