# Generated by Django 5.2.7 on 2025-12-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0041_ekipman_fikstur_remove_recetetalimatekipman_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fikstur',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.depo', verbose_name='Depo'),
        ),
        migrations.AddField(
            model_name='fikstur',
            name='raf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.raf', verbose_name='Raf'),
        ),
    ]
