# Generated by Django 5.2.7 on 2025-12-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0042_fikstur_depo_fikstur_raf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlcuAleti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=200, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('seri_no', models.CharField(max_length=100, unique=True, verbose_name='Seri No')),
                ('olcum_araligi', models.CharField(blank=True, max_length=200, verbose_name='Ölçüm Aralığı')),
                ('hassasiyet', models.CharField(blank=True, max_length=200, verbose_name='Hassasiyet')),
                ('kullanim_yeri', models.CharField(blank=True, max_length=200, verbose_name='Kullanım Yeri / İstasyon')),
                ('sorumlu_kisi', models.CharField(blank=True, max_length=200, verbose_name='Sorumlu Kişi')),
                ('kritiklik_seviyesi', models.CharField(choices=[('KRITIK', 'Kritik'), ('DESTEKLEYICI', 'Destekleyici')], default='DESTEKLEYICI', max_length=20, verbose_name='Kritiklik Seviyesi')),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('KARANTINADA', 'Karantinada'), ('HURDA', 'Hurda'), ('KALIBRASYONDA', 'Kalibrasyonda')], default='AKTIF', max_length=20, verbose_name='Durum')),
                ('kalibrasyon_periyot_tipi', models.CharField(choices=[('GUN', 'Gün'), ('HAFTA', 'Hafta'), ('AY', 'Ay'), ('YIL', 'Yıl')], default='YIL', max_length=10, verbose_name='Periyot Tipi')),
                ('kalibrasyon_periyot_sayisi', models.IntegerField(default=1, verbose_name='Periyot Sayısı')),
                ('son_kalibrasyon_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Kalibrasyon Tarihi')),
                ('sonraki_kalibrasyon_tarihi', models.DateField(blank=True, null=True, verbose_name='Bir Sonraki Kalibrasyon Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ölçü Aleti',
                'verbose_name_plural': 'Ölçü Aletleri',
                'ordering': ['seri_no'],
            },
        ),
        migrations.CreateModel(
            name='OlcuAletiTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Alet Türü')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ölçü Aleti Türü',
                'verbose_name_plural': 'Ölçü Aleti Türleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='KalibrasyonKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalibrasyon_tarihi', models.DateField(verbose_name='Kalibrasyon Tarihi')),
                ('kalibrasyon_tipi', models.CharField(choices=[('IC', 'İç (şirket içinde)'), ('DIS', 'Dış (akredite firma)')], max_length=10, verbose_name='Kalibrasyon Tipi')),
                ('standart_referansi', models.CharField(blank=True, max_length=200, verbose_name='Standart Referansı')),
                ('sonuc', models.CharField(choices=[('UYGUN', 'Uygun'), ('SARTLI_UYGUN', 'Şartlı Uygun'), ('UYGUNSUZ', 'Uygunsuz')], max_length=20, verbose_name='Sonuç')),
                ('sapma_degeri', models.CharField(blank=True, max_length=200, verbose_name='Sapma Değeri')),
                ('sertifika_rapor', models.FileField(blank=True, null=True, upload_to='kalibrasyonlar/', verbose_name='Sertifika / Rapor Dosyası (PDF)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olcu_aleti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalibrasyonlar', to='stokapp.olcualeti', verbose_name='Ölçü Aleti')),
            ],
            options={
                'verbose_name': 'Kalibrasyon Kaydı',
                'verbose_name_plural': 'Kalibrasyon Kayıtları',
                'ordering': ['-kalibrasyon_tarihi'],
            },
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='alet_turu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.olcualetituru', verbose_name='Alet Türü'),
        ),
    ]
