# Generated by Django 5.2.7 on 2025-12-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0043_olcualeti_olcualetituru_kalibrasyonkaydi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olcualeti',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='olcu_aletleri/', verbose_name='Cihaz Fotoğrafı'),
        ),
    ]
