# Generated by Django 5.2.7 on 2025-12-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0044_olcualeti_fotograf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PRODUCT', 'Ürün'), ('PRODUCT_REVISION', 'Ürün Revizyonu'), ('CUSTOMER', 'Müşteri'), ('CATEGORY', 'Kategori')], max_length=20, verbose_name='Kapsam')),
                ('product_revision', models.CharField(blank=True, max_length=50, verbose_name='Ürün Revizyonu')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Kategori')),
                ('severity_threshold', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Şiddet Eşiği')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('ACK_REQUIRED', 'Onay Gerekli'), ('BLOCK', 'Engelle')], default='INFO', max_length=20, verbose_name='Seviye')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('valid_from', models.DateTimeField(verbose_name='Geçerlilik Başlangıç')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stokapp.musteri', verbose_name='Müşteri')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Uyarı Kuralı',
                'verbose_name_plural': 'Uyarı Kuralları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPLAINT', 'Müşteri Şikayeti'), ('NCR', 'Uygunsuzluk (NCR)'), ('INTERNAL', 'İç Uygunsuzluk')], default='COMPLAINT', max_length=20, verbose_name='Tip')),
                ('product_revision', models.CharField(blank=True, max_length=50, verbose_name='Ürün Revizyonu')),
                ('lot_serial', models.CharField(blank=True, max_length=100, verbose_name='Lot/Seri No')),
                ('category', models.CharField(max_length=200, verbose_name='Kategori')),
                ('severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Şiddet (1-5)')),
                ('affected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Etkilenen Miktar')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('IN_REVIEW', 'İnceleniyor'), ('ACTIONED', 'Aksiyon Alındı'), ('VERIFIED', 'Doğrulandı'), ('CLOSED', 'Kapatıldı')], default='OPEN', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Tarihi')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.musteri', verbose_name='Müşteri')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.siparis', verbose_name='İlgili Sipariş')),
            ],
            options={
                'verbose_name': 'Şikayet/Uygunsuzluk',
                'verbose_name_plural': 'Şikayetler/Uygunsuzluklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Düzeltici Aksiyon'), ('PREVENTIVE', 'Önleyici Aksiyon')], max_length=20, verbose_name='Aksiyon Tipi')),
                ('root_cause_method', models.CharField(blank=True, choices=[('5WHY', '5 Why Analizi'), ('ISHIKAWA', 'Ishikawa (Balık Kılçığı)'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Kök Neden Analiz Yöntemi')),
                ('root_cause_text', models.TextField(verbose_name='Kök Neden')),
                ('action_text', models.TextField(verbose_name='Aksiyon')),
                ('due_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('verification_text', models.TextField(blank=True, verbose_name='Doğrulama')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('VERIFIED', 'Doğrulandı'), ('CLOSED', 'Kapatıldı')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_actions_owned', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_actions', to='stokapp.complaint', verbose_name='Şikayet')),
            ],
            options={
                'verbose_name': 'CAPA Aksiyonu',
                'verbose_name_plural': 'CAPA Aksiyonları',
                'ordering': ['due_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/%Y/%m/%d/', verbose_name='Dosya')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='stokapp.complaint', verbose_name='Şikayet')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Şikayet Eki',
                'verbose_name_plural': 'Şikayet Ekleri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=50, verbose_name='Revizyon')),
                ('effective_from', models.DateField(verbose_name='Geçerlilik Başlangıç Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Kontrol Planı',
                'verbose_name_plural': 'Kontrol Planları',
                'ordering': ['product', '-revision'],
                'unique_together': {('product', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='ControlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, null=True, verbose_name='Adım')),
                ('measurement_name', models.CharField(max_length=200, verbose_name='Ölçüm Adı')),
                ('spec_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Min. Spec')),
                ('spec_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max. Spec')),
                ('method', models.CharField(blank=True, max_length=200, verbose_name='Metod')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='Frekans')),
                ('required', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stokapp.controlplan', verbose_name='Kontrol Planı')),
            ],
            options={
                'verbose_name': 'Kontrol Planı Maddesi',
                'verbose_name_plural': 'Kontrol Planı Maddeleri',
                'ordering': ['step', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EcoChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('BOM', 'BOM (Bill of Materials)'), ('ROUTING', 'Yönlendirme'), ('CONTROL_FORM', 'Kontrol Formu'), ('INSTRUCTION', 'Talimat'), ('MATERIAL', 'Malzeme')], max_length=20, verbose_name='Değişiklik Tipi')),
                ('from_revision', models.CharField(blank=True, max_length=50, verbose_name='Önceki Revizyon')),
                ('to_revision', models.CharField(max_length=50, verbose_name='Yeni Revizyon')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('effective_from_date', models.DateField(verbose_name='Geçerlilik Başlangıç Tarihi')),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='DRAFT', max_length=20, verbose_name='Onay Durumu')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ecos', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_changes', to='stokapp.complaint', verbose_name='İlgili Şikayet')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ecos', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'ECO (Mühendislik Değişiklik Emri)',
                'verbose_name_plural': "ECO'lar (Mühendislik Değişiklik Emirleri)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='İçerik Tipi')),
                ('object_id', models.IntegerField(verbose_name='Nesne ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Oluşturuldu'), ('UPDATE', 'Güncellendi'), ('DELETE', 'Silindi'), ('STATUS_CHANGE', 'Durum Değişikliği'), ('APPROVE', 'Onaylandı'), ('REJECT', 'Reddedildi')], max_length=20, verbose_name='Aksiyon Tipi')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Alan Adı')),
                ('old_value', models.TextField(blank=True, verbose_name='Eski Değer')),
                ('new_value', models.TextField(blank=True, verbose_name='Yeni Değer')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Loglar',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='stokapp_aud_content_1234e4_idx'), models.Index(fields=['timestamp'], name='stokapp_aud_timesta_0cf87f_idx')],
            },
        ),
    ]
