# Generated by Django 5.2.7 on 2025-12-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0046_in_process_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(verbose_name='Hata Mesajı')),
                ('seviye', models.CharField(choices=[('ERROR', 'Hata'), ('WARNING', 'Uyarı'), ('INFO', 'Bilgi'), ('SUCCESS', 'Başarılı')], default='ERROR', max_length=20, verbose_name='Seviye')),
                ('kaynak', models.CharField(blank=True, help_text='Hatanın oluştuğu view/fonksiyon', max_length=200, verbose_name='Kaynak')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('detay', models.TextField(blank=True, verbose_name='Detaylı Hata Bilgisi')),
                ('cozuldu', models.BooleanField(default=False, verbose_name='Çözüldü mü?')),
                ('cozum_notu', models.TextField(blank=True, verbose_name='Çözüm Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Hata Raporu',
                'verbose_name_plural': 'Hata Raporları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='workorderinspection',
            new_name='stokapp_wor_work_or_039c0b_idx',
            old_name='stokapp_wor_work_or_6f8a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderinspection',
            new_name='stokapp_wor_control_93d302_idx',
            old_name='stokapp_wor_control_c8b3e1_idx',
        ),
        migrations.AlterField(
            model_name='controlitem',
            name='method',
            field=models.CharField(blank=True, help_text='Örn: Kumpas, Mikrometre, CMM, Gözle muayene', max_length=200, verbose_name='Ölçüm Metodu'),
        ),
        migrations.AlterField(
            model_name='controlitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='hatalog',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='hatalog',
            index=models.Index(fields=['-created_at'], name='stokapp_hat_created_fb7297_idx'),
        ),
        migrations.AddIndex(
            model_name='hatalog',
            index=models.Index(fields=['seviye'], name='stokapp_hat_seviye_ba2584_idx'),
        ),
        migrations.AddIndex(
            model_name='hatalog',
            index=models.Index(fields=['cozuldu'], name='stokapp_hat_cozuldu_74fee2_idx'),
        ),
    ]
