# Generated by Django 5.2.7 on 2025-12-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0048_stokitem_stok_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteTalimatOlcuAleti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('olcu_aleti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.olcualeti', verbose_name='Ölçü Aleti')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olcu_aletleri', to='stokapp.recetetalimat')),
            ],
            options={
                'verbose_name': 'Talimat Ölçü Aleti',
                'verbose_name_plural': 'Talimat Ölçü Aletleri',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
