# Generated by Django 5.2.7 on 2025-12-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0049_recetetalimatolcualeti'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurulumDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_parcasi', models.CharField(help_text='Örn: Alt Plaka, Üst Plaka, Yan Duvar', max_length=200, verbose_name='Ürün Parçası')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('versiyon', models.CharField(default='1.0', help_text='Örn: 1.0, 1.1, 2.0', max_length=50, verbose_name='Versiyon')),
                ('pdf_dosya', models.FileField(upload_to='kurulum_dosyalari/%Y/%m/%d/', verbose_name='PDF Dosyası')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('istasyon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.istasyon', verbose_name='İstasyon')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurulum_dosyalari', to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Kurulum Dosyası',
                'verbose_name_plural': 'Kurulum Dosyaları',
                'ordering': ['urun__stok_kodu', 'urun_parcasi', '-versiyon'],
            },
        ),
        migrations.CreateModel(
            name='KurulumDosyasiArsiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_dosya', models.FileField(upload_to='kurulum_dosyalari/arsiv/%Y/%m/%d/', verbose_name='PDF Dosyası')),
                ('versiyon', models.CharField(max_length=50, verbose_name='Versiyon')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('arsiv_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Arşivlenme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurulum_dosyasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsivlenmis_versiyonlar', to='stokapp.kurulumdosyasi', verbose_name='Kurulum Dosyası')),
            ],
            options={
                'verbose_name': 'Arşivlenmiş Kurulum Dosyası',
                'verbose_name_plural': 'Arşivlenmiş Kurulum Dosyaları',
                'ordering': ['-arsiv_tarihi'],
            },
        ),
    ]
