# Generated by Django 5.2.7 on 2025-12-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0050_kurulumdosyasi_kurulumdosyasiarsiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteTalimatAciklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_aciklamalar', to='stokapp.recetetalimat', verbose_name='Talimat')),
            ],
            options={
                'verbose_name': 'Talimat Ek Açıklaması',
                'verbose_name_plural': 'Talimat Ek Açıklamaları',
                'ordering': ['sira', 'created_at'],
            },
        ),
    ]
