# Generated by Django 5.2.7 on 2025-12-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0051_recetetalimataciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceteTalimatKurulumDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurulum_dosyasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stokapp.kurulumdosyasi', verbose_name='Kurulum Dosyası')),
                ('talimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurulum_dosyalari', to='stokapp.recetetalimat', verbose_name='Talimat')),
            ],
            options={
                'verbose_name': 'Talimat Kurulum Dosyası',
                'verbose_name_plural': 'Talimat Kurulum Dosyaları',
                'ordering': ['sira', 'created_at'],
                'unique_together': {('talimat', 'kurulum_dosyasi')},
            },
        ),
    ]
