# Generated by Django 5.2.7 on 2026-01-08 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0052_recetetalimatkurulumdosyasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('digital_caliper', 'Dijital Kumpas'), ('analog_caliper', 'Analog Kumpas'), ('outside_micrometer', 'Dış Mikrometre'), ('inside_micrometer', 'İç Mikrometre'), ('coating_thickness_gauge', 'Kaplama Kalınlık Ölçer'), ('roughness_tester', 'Pürüzlülük Ölçer'), ('hardness_tester', 'Sertlik Ölçer')], max_length=50, verbose_name='Cihaz Tipi')),
                ('min_range', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Minimum Aralık')),
                ('max_range', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Maximum Aralık')),
                ('tolerance_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tolerans Değeri')),
                ('tolerance_unit', models.CharField(choices=[('mm', 'Milimetre (mm)'), ('%', 'Yüzde (%)'), ('HRC', 'Rockwell C Sertliği'), ('Ra', 'Pürüzlülük (Ra)')], default='mm', max_length=10, verbose_name='Tolerans Birimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kalibrasyon Toleransı',
                'verbose_name_plural': 'Kalibrasyon Toleransları',
                'ordering': ['device_type', 'min_range'],
            },
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kalibrasyon Tarihi (Yeni)'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='calibration_type',
            field=models.CharField(blank=True, choices=[('routine', 'Rutin Kalibrasyon'), ('after_impact', 'Darbe Sonrası'), ('verification', 'Doğrulama')], max_length=20, verbose_name='Kalibrasyon Tipi'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='controlled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_controlled', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='environment_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortam Nem (%)'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='environment_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortam Sıcaklığı (°C)'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sonraki Kalibrasyon Tarihi'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='reference_used',
            field=models.CharField(blank=True, help_text='Örn: blok mastar, üretici mastarı, test plakası, sertlik bloğu', max_length=200, verbose_name='Kullanılan Referans'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Açıklama/Notlar'),
        ),
        migrations.AddField(
            model_name='kalibrasyonkaydi',
            name='result',
            field=models.CharField(blank=True, choices=[('suitable', 'Uygun'), ('conditional', 'Şartlı Uygun'), ('unsuitable', 'Uygunsuz')], max_length=20, verbose_name='Sonuç'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='calibration_method',
            field=models.CharField(blank=True, choices=[('internal_reference', 'İç Referans (Şirket İçi)'), ('external_accredited', 'Dış Akredite (Akredite Firma)')], max_length=30, verbose_name='Kalibrasyon Yöntemi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='calibration_period_months',
            field=models.IntegerField(default=12, help_text='Aylar cinsinden', verbose_name='Kalibrasyon Periyodu (Ay)'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Departman/Bölüm'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='device_id',
            field=models.CharField(blank=True, help_text='Örn: KMP-001, MIC-075', max_length=100, null=True, unique=True, verbose_name='Cihaz ID'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='device_type',
            field=models.CharField(blank=True, choices=[('digital_caliper', 'Dijital Kumpas'), ('analog_caliper', 'Analog Kumpas'), ('outside_micrometer', 'Dış Mikrometre'), ('inside_micrometer', 'İç Mikrometre'), ('coating_thickness_gauge', 'Kaplama Kalınlık Ölçer'), ('roughness_tester', 'Pürüzlülük Ölçer'), ('hardness_tester', 'Sertlik Ölçer')], max_length=50, verbose_name='Cihaz Tipi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kalibrasyon Tarihi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bir Sonraki Kalibrasyon Tarihi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('blocked', 'Blokeli'), ('out_of_service', 'Hizmet Dışı')], default='active', max_length=20, verbose_name='Durum (Status)'),
        ),
        migrations.AlterField(
            model_name='kalibrasyonkaydi',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama (Eski)'),
        ),
        migrations.AlterField(
            model_name='kalibrasyonkaydi',
            name='kalibrasyon_tipi',
            field=models.CharField(blank=True, choices=[('IC', 'İç (şirket içinde)'), ('DIS', 'Dış (akredite firma)')], max_length=10, verbose_name='Kalibrasyon Tipi (Eski)'),
        ),
        migrations.AlterField(
            model_name='kalibrasyonkaydi',
            name='sonuc',
            field=models.CharField(blank=True, choices=[('UYGUN', 'Uygun'), ('SARTLI_UYGUN', 'Şartlı Uygun'), ('UYGUNSUZ', 'Uygunsuz')], max_length=20, verbose_name='Sonuç (Eski)'),
        ),
        migrations.AlterField(
            model_name='olcualeti',
            name='alet_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.olcualetituru', verbose_name='Alet Türü'),
        ),
        migrations.AlterField(
            model_name='olcualeti',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('KARANTINADA', 'Karantinada'), ('HURDA', 'Hurda'), ('KALIBRASYONDA', 'Kalibrasyonda')], default='AKTIF', max_length=20, verbose_name='Durum (Eski)'),
        ),
        migrations.AlterField(
            model_name='olcualeti',
            name='olcum_araligi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ölçüm Aralığı (Measurement Range)'),
        ),
        migrations.AlterField(
            model_name='olcualeti',
            name='son_kalibrasyon_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kalibrasyon Tarihi (Eski)'),
        ),
        migrations.AlterField(
            model_name='olcualeti',
            name='sonraki_kalibrasyon_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Bir Sonraki Kalibrasyon Tarihi (Eski)'),
        ),
        migrations.CreateModel(
            name='CalibrationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Referans Değer')),
                ('measurement_1', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ölçüm 1')),
                ('measurement_2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ölçüm 2')),
                ('measurement_3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ölçüm 3')),
                ('average_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Ortalama Değer')),
                ('deviation', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sapma')),
                ('result', models.CharField(blank=True, choices=[('pass', 'Geçti'), ('fail', 'Geçmedi')], max_length=10, verbose_name='Sonuç')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='stokapp.kalibrasyonkaydi', verbose_name='Kalibrasyon Kaydı')),
            ],
            options={
                'verbose_name': 'Kalibrasyon Ölçümü',
                'verbose_name_plural': 'Kalibrasyon Ölçümleri',
                'ordering': ['reference_value'],
            },
        ),
        migrations.RunPython(
            # Mevcut ölçü aletleri için device_id'yi seri_no'dan otomatik doldur
            code=lambda apps, schema_editor: _populate_device_ids(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _populate_device_ids(apps, schema_editor):
    """Mevcut ölçü aletleri için device_id'yi seri_no'dan doldur"""
    OlcuAleti = apps.get_model('stokapp', 'OlcuAleti')
    for alet in OlcuAleti.objects.filter(device_id__isnull=True):
        if alet.seri_no:
            # Benzersiz olup olmadığını kontrol et
            counter = 1
            device_id = alet.seri_no
            while OlcuAleti.objects.filter(device_id=device_id).exists():
                device_id = f"{alet.seri_no}_{counter}"
                counter += 1
            alet.device_id = device_id
            alet.save(update_fields=['device_id'])
