# Generated by Django 5.2.7 on 2026-01-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0053_calibrationtolerance_kalibrasyonkaydi_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olcualeti',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='satın_alma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Satın Alma Tarihi'),
        ),
    ]
