# Generated by Django 5.2.7 on 2026-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0054_olcualeti_purchase_date_olcualeti_satın_alma_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olcualeti',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='dis_kalibrasyon_gerekli',
            field=models.BooleanField(default=False, verbose_name='Dış Kalibrasyon Gerekli'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='dis_kalibrasyon_periyot_sayisi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dış Kalibrasyon Periyot Sayısı'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='dis_kalibrasyon_periyot_tipi',
            field=models.CharField(blank=True, choices=[('GUN', 'Gün'), ('HAFTA', 'Hafta'), ('AY', 'Ay'), ('YIL', 'Yıl')], max_length=10, verbose_name='Dış Kalibrasyon Periyot Tipi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='dis_kalibrasyon_son_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Dış Kalibrasyon Son Tarihi'),
        ),
        migrations.AddField(
            model_name='olcualeti',
            name='dis_kalibrasyon_sonraki_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Dış Kalibrasyon Sonraki Tarihi'),
        ),
    ]
