# Generated by Django 5.2.7 on 2026-01-09 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0055_remove_olcualeti_purchase_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CncProgram',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Program ID')),
                ('machine_type', models.CharField(choices=[('cnc_lathe', 'CNC Torna'), ('cnc_mill', 'CNC Freze')], max_length=20, verbose_name='Makine Tipi')),
                ('machine_name', models.CharField(blank=True, help_text='Örn: Doosan Lynx, Haas VF2', max_length=200, null=True, verbose_name='Makine Adı')),
                ('program_name', models.CharField(help_text='Örn: BD410_TORNA_OP10', max_length=200, verbose_name='Program Adı')),
                ('program_number', models.CharField(blank=True, help_text='Örn: O1234', max_length=100, verbose_name='Program Numarası')),
                ('file_format', models.CharField(choices=[('nc', 'NC'), ('txt', 'TXT')], default='nc', max_length=10, verbose_name='Dosya Formatı')),
                ('current_revision', models.CharField(blank=True, help_text='Örn: R01, R02', max_length=20, verbose_name='Aktif Revizyon')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('archived', 'Arşivlenmiş')], default='active', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnc_programs', to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'CNC Program',
                'verbose_name_plural': 'CNC Programlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CncProgramRevision',
            fields=[
                ('revision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Revizyon ID')),
                ('revision_code', models.CharField(help_text='Örn: R01, R02, R03', max_length=20, verbose_name='Revizyon Kodu')),
                ('revision_type', models.CharField(choices=[('new', 'Yeni Program'), ('correction', 'Düzeltme'), ('optimization', 'Optimizasyon'), ('emergency_fix', 'Acil Düzeltme')], max_length=20, verbose_name='Revizyon Tipi')),
                ('file_path', models.FileField(help_text='.nc veya .txt dosyası', upload_to='cnc_programs/%Y/%m/%d/', verbose_name='Program Dosyası')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash değeri', max_length=64, verbose_name='Dosya Hash')),
                ('revision_note', models.TextField(help_text='Örn: OP10 paso derinliği düşürüldü, chatter problemi giderildi.', verbose_name='Revizyon Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_program_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='stokapp.cncprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'CNC Program Revizyonu',
                'verbose_name_plural': 'CNC Program Revizyonları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CncProgramLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Log ID')),
                ('action', models.CharField(choices=[('created', 'Oluşturuldu'), ('revision_added', 'Revizyon Eklendi'), ('revision_activated', 'Revizyon Aktifleştirildi'), ('revision_rolled_back', 'Revizyon Geri Alındı'), ('file_downloaded', 'Dosya İndirildi'), ('archived', 'Arşivlendi'), ('deleted', 'Silindi')], max_length=30, verbose_name='İşlem')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stokapp.cncprogram', verbose_name='Program')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_program_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='stokapp.cncprogramrevision', verbose_name='Revizyon')),
            ],
            options={
                'verbose_name': 'CNC Program Log',
                'verbose_name_plural': 'CNC Program Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uretimasamasi',
            name='cnc_program_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_asamalari', to='stokapp.cncprogramrevision', verbose_name='Kullanılan CNC Program'),
        ),
        migrations.AddIndex(
            model_name='cncprogram',
            index=models.Index(fields=['product'], name='stokapp_cnc_product_906795_idx'),
        ),
        migrations.AddIndex(
            model_name='cncprogram',
            index=models.Index(fields=['status'], name='stokapp_cnc_status_1e2eca_idx'),
        ),
        migrations.AddIndex(
            model_name='cncprogram',
            index=models.Index(fields=['machine_type'], name='stokapp_cnc_machine_6990ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cncprogramrevision',
            index=models.Index(fields=['program', 'is_active'], name='stokapp_cnc_program_20d092_idx'),
        ),
        migrations.AddIndex(
            model_name='cncprogramrevision',
            index=models.Index(fields=['created_at'], name='stokapp_cnc_created_6ff776_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cncprogramrevision',
            unique_together={('program', 'revision_code')},
        ),
        migrations.AddIndex(
            model_name='cncprogramlog',
            index=models.Index(fields=['program', '-created_at'], name='stokapp_cnc_program_cadac8_idx'),
        ),
        migrations.AddIndex(
            model_name='cncprogramlog',
            index=models.Index(fields=['action'], name='stokapp_cnc_action_6e8d6d_idx'),
        ),
    ]
