# Generated by Django 5.2.7 on 2026-01-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0056_cncprogram_cncprogramrevision_cncprogramlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Tekmar Depo Sigortası 2026', max_length=500, verbose_name='Başlık')),
                ('issuer_authority', models.CharField(help_text='Örn: TSE, SGK, Sigorta Şirketi', max_length=200, verbose_name='Veren Makam/Kurum')),
                ('issue_date', models.DateField(verbose_name='Evrak Tarihi')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('document_no', models.CharField(blank=True, max_length=200, verbose_name='Belge Numarası/Seri')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRING', 'Süresi Yaklaşıyor'), ('EXPIRED', 'Süresi Dolmuş'), ('PENDING_RENEWAL', 'Yenileme Bekliyor'), ('CANCELLED', 'İptal Edilmiş'), ('ARCHIVED', 'Arşivlenmiş')], default='ACTIVE', max_length=30, verbose_name='Durum')),
                ('risk_level', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek')], default='MEDIUM', max_length=20, verbose_name='Risk Seviyesi')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('confidentiality', models.CharField(choices=[('INTERNAL', 'İç Kullanım'), ('CONFIDENTIAL', 'Gizli'), ('PUBLIC', 'Genel')], default='INTERNAL', max_length=20, verbose_name='Gizlilik')),
                ('requires_original', models.BooleanField(default=False, verbose_name='Aslı Gerekir')),
                ('storage_location', models.CharField(blank=True, help_text='Klasör/Raf bilgisi', max_length=500, verbose_name='Fiziksel Depolama Yeri')),
                ('renewal_required', models.BooleanField(default=True, verbose_name='Yenileme Gerekli')),
                ('renewal_lead_days', models.IntegerField(default=60, help_text='Kaç gün önce yenileme başlatılmalı', verbose_name='Yenileme Öncesi Gün')),
                ('tags', models.TextField(blank=True, help_text='Virgülle ayrılmış etiketler', verbose_name='Etiketler')),
                ('notes_internal', models.TextField(blank=True, verbose_name='İç Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('owner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: ISO9001, CE, SGK, VERGI_LEVHASI', max_length=100, unique=True, verbose_name='Kod')),
                ('name', models.CharField(help_text='Örn: ISO 9001 Sertifikası', max_length=200, verbose_name='Ad')),
                ('category', models.CharField(choices=[('Ruhsat', 'Ruhsat'), ('İzin', 'İzin'), ('Sertifika', 'Sertifika'), ('Sözleşme', 'Sözleşme'), ('Sigorta', 'Sigorta'), ('Uygunluk', 'Uygunluk'), ('Diğer', 'Diğer')], max_length=50, verbose_name='Kategori')),
                ('default_risk_level', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek')], default='MEDIUM', max_length=20, verbose_name='Varsayılan Risk Seviyesi')),
                ('default_reminder_days', models.TextField(blank=True, help_text='JSON array: [90,60,30,7]', verbose_name='Varsayılan Hatırlatma Günleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Belge Türü',
                'verbose_name_plural': 'Belge Türleri',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='stokapp_doc_categor_d52c64_idx'), models.Index(fields=['code'], name='stokapp_doc_code_04c193_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(verbose_name='Kaç Gün Önce')),
                ('channel', models.CharField(choices=[('IN_APP', 'Uygulama İçi'), ('EMAIL', 'E-posta')], default='IN_APP', max_length=20, verbose_name='Kanal')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='stokapp.document', verbose_name='Belge (Özel)')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='stokapp.documenttype', verbose_name='Belge Türü (Genel)')),
            ],
            options={
                'verbose_name': 'Belge Hatırlatması',
                'verbose_name_plural': 'Belge Hatırlatmaları',
                'ordering': ['days_before'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='stokapp.documenttype', verbose_name='Belge Türü'),
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Oluşturuldu'), ('UPDATED', 'Güncellendi'), ('FILE_UPLOADED', 'Dosya Yüklendi'), ('STATUS_CHANGED', 'Durum Değişti'), ('REMINDER_SENT', 'Hatırlatma Gönderildi'), ('RENEWAL_STARTED', 'Yenileme Başlatıldı'), ('RENEWAL_COMPLETED', 'Yenileme Tamamlandı'), ('DELETED_SOFT', 'Silindi (Soft)'), ('DOWNLOADED', 'İndirildi')], max_length=30, verbose_name='Olay Tipi')),
                ('payload', models.TextField(blank=True, help_text='JSON formatında ek bilgiler', verbose_name='Ek Bilgi (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_events', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stokapp.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'Belge Olayı',
                'verbose_name_plural': 'Belge Olayları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='stokapp_doc_documen_118686_idx'), models.Index(fields=['event_type'], name='stokapp_doc_event_t_a54db3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.IntegerField(default=1, verbose_name='Versiyon Numarası')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Dosya')),
                ('file_name_original', models.CharField(max_length=500, verbose_name='Orijinal Dosya Adı')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Tipi')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 Checksum')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('change_note', models.TextField(blank=True, verbose_name='Değişiklik Notu')),
                ('is_current', models.BooleanField(default=True, verbose_name='Güncel Dosya')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stokapp.document', verbose_name='Belge')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_files', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Belge Dosyası',
                'verbose_name_plural': 'Belge Dosyaları',
                'ordering': ['-version_no'],
                'indexes': [models.Index(fields=['document', 'is_current'], name='stokapp_doc_documen_593fe6_idx'), models.Index(fields=['document', 'version_no'], name='stokapp_doc_documen_4002cb_idx')],
                'unique_together': {('document', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_entity_type', models.CharField(choices=[('ASSET', 'Demirbaş'), ('VEHICLE', 'Araç'), ('FACILITY', 'Tesis'), ('CUSTOMER', 'Müşteri'), ('CONTRACT', 'Sözleşme'), ('PROJECT', 'Proje'), ('OTHER', 'Diğer')], max_length=50, verbose_name='Bağlı Varlık Tipi')),
                ('linked_entity_id', models.PositiveIntegerField(verbose_name='Bağlı Varlık ID')),
                ('relation', models.CharField(default='covers', help_text='covers, required_for, belongs_to', max_length=100, verbose_name='İlişki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='stokapp.document', verbose_name='Belge')),
            ],
            options={
                'verbose_name': 'Belge İlişkisi',
                'verbose_name_plural': 'Belge İlişkileri',
                'indexes': [models.Index(fields=['linked_entity_type', 'linked_entity_id'], name='stokapp_doc_linked__2f78bc_idx'), models.Index(fields=['document'], name='stokapp_doc_documen_d494d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('renewal_due_date', models.DateField(blank=True, null=True, verbose_name='Hedef Tarih')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REQUESTED', 'Talep Edildi'), ('IN_PROGRESS', 'Devam Ediyor'), ('SUBMITTED', 'Başvuruldu'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('external_reference', models.CharField(blank=True, help_text='Başvuru no / e-devlet takip no', max_length=200, verbose_name='Dış Referans')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='stokapp.document', verbose_name='Belge')),
                ('new_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='stokapp.document', verbose_name='Yeni Belge')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name': 'Belge Yenileme',
                'verbose_name_plural': 'Belge Yenilemeleri',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='stokapp_doc_documen_6c29b5_idx'), models.Index(fields=['requested_at'], name='stokapp_doc_request_c6c027_idx'), models.Index(fields=['status'], name='stokapp_doc_status_4f7c6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type', 'status'], name='stokapp_doc_type_id_095013_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['valid_until'], name='stokapp_doc_valid_u_a4a58c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner_user'], name='stokapp_doc_owner_u_5251a0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['risk_level'], name='stokapp_doc_risk_le_cb5aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='stokapp_doc_status_5773f8_idx'),
        ),
    ]
