# Generated by Django 5.2.7 on 2026-03-29 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0060_siparis_red_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uretimasamasi',
            name='duraklatma_toplam_saniye',
            field=models.IntegerField(default=0, verbose_name='Toplam Duraklatma Süresi (sn)'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_durumu',
            field=models.CharField(choices=[('ONAY_BEKLIYOR', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('RED', 'Red')], default='ONAY_BEKLIYOR', max_length=20, verbose_name='Sipariş Durumu'),
        ),
        migrations.AlterField(
            model_name='uretimasamasi',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('DEVAM_EDIYOR', 'Devam Ediyor'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı'), ('SORUNLU', 'Sorunlu / Durduruldu')], default='BEKLIYOR', max_length=20),
        ),
        migrations.CreateModel(
            name='UretimAsamaDurusKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslama_zamani', models.DateTimeField()),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True)),
                ('sure_saniye', models.IntegerField(default=0)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durus_kayitlari', to='stokapp.uretimasamasi')),
            ],
            options={
                'verbose_name': 'Üretim Aşama Duruş Kaydı',
                'verbose_name_plural': 'Üretim Aşama Duruş Kayıtları',
                'ordering': ['-baslama_zamani'],
            },
        ),
        migrations.CreateModel(
            name='UretimAsamaNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_metni', models.TextField(verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_kayitlari', to='stokapp.uretimasamasi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_asama_notlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üretim Aşama Notu',
                'verbose_name_plural': 'Üretim Aşama Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UretimAsamaSorun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorun_tipi', models.CharField(choices=[('MALZEME_EKSIK', 'Malzeme eksik'), ('TAKIM_PROBLEMI', 'Takım problemi'), ('OLCU_PROBLEMI', 'Ölçü problemi'), ('TEKNIK_RESIM_UYUMSUZ', 'Teknik resim uyumsuzluğu'), ('MAKINE_ARIZASI', 'Makine arızası'), ('DIGER', 'Diğer')], default='DIGER', max_length=30)),
                ('aciklama', models.TextField()),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='uretim_asama_sorun/%Y/%m/%d/')),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('KAPALI', 'Kapalı')], default='ACIK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorun_kayitlari', to='stokapp.uretimasamasi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_asama_sorunlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üretim Aşama Sorunu',
                'verbose_name_plural': 'Üretim Aşama Sorunları',
                'ordering': ['-created_at'],
            },
        ),
    ]
