# Generated by Django 5.2.7 on 2026-03-29 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_default_materials(apps, schema_editor):
    ToolMaterial = apps.get_model("stokapp", "ToolMaterial")
    for name in ["ST", "Paslanmaz", "1040", "4140", "2379", "2436"]:
        ToolMaterial.objects.get_or_create(name=name)


def unseed_default_materials(apps, schema_editor):
    ToolMaterial = apps.get_model("stokapp", "ToolMaterial")
    ToolMaterial.objects.filter(name__in=["ST", "Paslanmaz", "1040", "4140", "2379", "2436"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0064_alter_stokhareketi_hareket_tipi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('tool_type', models.CharField(choices=[('drill', 'Matkap'), ('endmill', 'Freze'), ('reamer', 'Rayba'), ('tap', 'Kılavuz'), ('other', 'Diğer')], max_length=20)),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Çap (mm)')),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('coating', models.CharField(blank=True, max_length=120)),
                ('max_cutting_mm', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_cutting_mm', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('worn', 'Körelmiş'), ('broken', 'Kırılmış'), ('scrapped', 'Hurda')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'db_table': 'tools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Malzemesi',
                'verbose_name_plural': 'Takım Malzemeleri',
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_reason', models.CharField(choices=[('broken', 'Kırıldı'), ('worn', 'Köreldi')], max_length=20)),
                ('cutting_mm_at_change', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_changes', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='stokapp.tool')),
            ],
            options={
                'verbose_name': 'Takım Değişim Kaydı',
                'verbose_name_plural': 'Takım Değişim Kayıtları',
                'db_table': 'tool_changes',
                'ordering': ['-change_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceteOperasyonTakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(blank=True, choices=[('drill', 'Matkap'), ('endmill', 'Freze'), ('reamer', 'Rayba'), ('tap', 'Kılavuz'), ('other', 'Diğer')], max_length=20)),
                ('hole_count', models.PositiveIntegerField(default=1, verbose_name='Delik Sayısı')),
                ('hole_depth_mm', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tek Delik Boyu (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recete_operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takim_kullanimlari', to='stokapp.receteoperasyon')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_links', to='stokapp.tool')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_tools', to='stokapp.toolmaterial')),
            ],
            options={
                'verbose_name': 'Reçete Operasyon Takımı',
                'verbose_name_plural': 'Reçete Operasyon Takımları',
                'db_table': 'recipe_tools',
                'ordering': ['recete_operasyon__sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_mm', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='stokapp.toolmaterial')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usage_logs', to='stokapp.uretimasamasi')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='stokapp.tool')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usage_logs', to='stokapp.uretimemri')),
            ],
            options={
                'verbose_name': 'Takım Kullanım Kaydı',
                'verbose_name_plural': 'Takım Kullanım Kayıtları',
                'db_table': 'tool_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool', 'created_at'], name='tool_usage__tool_id_287b7e_idx'), models.Index(fields=['material', 'created_at'], name='tool_usage__materia_3faebc_idx')],
            },
        ),
        migrations.RunPython(seed_default_materials, unseed_default_materials),
    ]
