# Generated by Django 5.2.7 on 2026-03-29 19:51

import django.db.models.deletion
from django.db import migrations, models


def seed_tool_type_options(apps, schema_editor):
    ToolTypeOption = apps.get_model("stokapp", "ToolTypeOption")
    Tool = apps.get_model("stokapp", "Tool")
    defaults = [
        ("Matkap", "DR"),
        ("Freze", "EM"),
        ("Rayba", "RM"),
        ("Kılavuz", "TP"),
        ("Diğer", "TL"),
    ]
    for name, prefix in defaults:
        ToolTypeOption.objects.get_or_create(name=name, defaults={"prefix": prefix, "aktif": True})

    for tool in Tool.objects.all():
        if not tool.tool_type:
            continue
        option = ToolTypeOption.objects.filter(name=tool.tool_type).first()
        if option:
            tool.tool_type_option_id = option.id
            tool.save(update_fields=["tool_type_option"])


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0065_tool_toolmaterial_toolchange_receteoperasyontakim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBodyMaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Malzemesi',
                'verbose_name_plural': 'Takım Malzemeleri',
                'db_table': 'tool_body_material_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolBrandOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Markası',
                'verbose_name_plural': 'Takım Markaları',
                'db_table': 'tool_brand_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolCoatingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Kaplaması',
                'verbose_name_plural': 'Takım Kaplamaları',
                'db_table': 'tool_coating_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolModelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Model Numarası',
                'verbose_name_plural': 'Takım Model Numaraları',
                'db_table': 'tool_model_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Takım Tipi',
                'verbose_name_plural': 'Takım Tipleri',
                'db_table': 'tool_type_options',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='model_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='receteoperasyontakim',
            name='tool_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='tool',
            name='body_material_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='stokapp.toolbodymaterialoption'),
        ),
        migrations.AddField(
            model_name='tool',
            name='brand_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='stokapp.toolbrandoption'),
        ),
        migrations.AddField(
            model_name='tool',
            name='coating_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='stokapp.toolcoatingoption'),
        ),
        migrations.AddField(
            model_name='tool',
            name='model_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='stokapp.toolmodeloption'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='stokapp.tooltypeoption'),
        ),
        migrations.RunPython(seed_tool_type_options, migrations.RunPython.noop),
    ]
