# Generated by Django 5.2.7 on 2026-03-29 20:37

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _decimal_cutting_mm(tool):
    raw = getattr(tool, "total_cutting_mm", None) or 0
    try:
        return Decimal(str(raw))
    except Exception:
        return Decimal("0")


def create_initial_tool_lives(apps, schema_editor):
    """
    Aynı migration hem default PostgreSQL hem --database=sqlite_backup ile çalışabilsin diye
    tüm ORM erişimi schema_editor.connection.alias üzerinden yapılır.
    uniq_tool_single_active_life (takım başına tek aktif ömür) ihlal etmemek için
    önce aktif ömür aranır; yoksa (tool, life_no=1) için get_or_create kullanılır.
    """
    db_alias = schema_editor.connection.alias
    Tool = apps.get_model("stokapp", "Tool")
    ToolLifeCycle = apps.get_model("stokapp", "ToolLifeCycle")
    ToolUsageLog = apps.get_model("stokapp", "ToolUsageLog")
    ToolChange = apps.get_model("stokapp", "ToolChange")

    for tool in Tool.objects.using(db_alias).iterator():
        life = (
            ToolLifeCycle.objects.using(db_alias)
            .filter(tool_id=tool.pk, status="active")
            .order_by("life_no", "pk")
            .first()
        )
        if life is None:
            life, _created = ToolLifeCycle.objects.using(db_alias).get_or_create(
                tool_id=tool.pk,
                life_no=1,
                defaults={
                    "start_date": django.utils.timezone.now(),
                    "cutting_mm": _decimal_cutting_mm(tool),
                    "status": "active",
                },
            )
        # Aktif ömür zaten varken mevcut satırı değiştirmiyoruz (veri bütünlüğü).

        ToolUsageLog.objects.using(db_alias).filter(
            tool_id=tool.pk, life_cycle_id__isnull=True
        ).update(life_cycle_id=life.pk)
        ToolChange.objects.using(db_alias).filter(
            tool_id=tool.pk, life_cycle_id__isnull=True
        ).update(life_cycle_id=life.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0066_toolbodymaterialoption_toolbrandoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolchange',
            name='change_reason',
            field=models.CharField(choices=[('broken', 'Kırıldı'), ('worn', 'Köreldi'), ('regrind', 'Bilemeye Gönderildi')], max_length=20),
        ),
        migrations.CreateModel(
            name='ToolLifeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_no', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cutting_mm', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('finished', 'Tamamlandı')], default='active', max_length=12)),
                ('change_reason', models.CharField(blank=True, choices=[('worn', 'Körelme'), ('broken', 'Kırılma'), ('regrind', 'Bileme')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_cycles', to='stokapp.tool')),
            ],
            options={
                'verbose_name': 'Takım Ömrü',
                'verbose_name_plural': 'Takım Ömürleri',
                'db_table': 'tool_life_cycles',
                'ordering': ['-life_no'],
            },
        ),
        migrations.AddField(
            model_name='toolchange',
            name='life_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='stokapp.toollifecycle'),
        ),
        migrations.AddField(
            model_name='toolusagelog',
            name='life_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='stokapp.toollifecycle'),
        ),
        migrations.AddConstraint(
            model_name='toollifecycle',
            constraint=models.UniqueConstraint(fields=('tool', 'life_no'), name='uniq_tool_life_no'),
        ),
        migrations.AddConstraint(
            model_name='toollifecycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tool',), name='uniq_tool_single_active_life'),
        ),
        migrations.RunPython(create_initial_tool_lives, migrations.RunPython.noop),
    ]
