# Generated by Django 5.2.7 on 2026-04-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0067_alter_toolchange_change_reason_toollifecycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalma',
            name='siparis_formu_mail_gonderildi_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sipariş formu mail gönderimi'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='teklif_girisi_kaydedildi_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teklif girişi kaydı'),
        ),
        migrations.AddField(
            model_name='satinalma',
            name='teklif_talep_mail_gonderildi_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teklif talep formu mail gönderimi'),
        ),
    ]
