# Generated by Django 5.2.7 on 2026-04-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0068_satinalma_mail_teklif_takip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifSartSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teklif şart şablonu',
                'verbose_name_plural': 'Teklif şart şablonları',
                'db_table': 'offer_conditions',
                'ordering': ['baslik'],
            },
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='siparis_formu_mail_gonderildi_at',
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='teklif_girisi_kaydedildi_at',
        ),
        migrations.RemoveField(
            model_name='satinalma',
            name='teklif_talep_mail_gonderildi_at',
        ),
        migrations.AlterField(
            model_name='sipariskalemi',
            name='stok_item',
            field=models.ForeignKey(blank=True, help_text='Serbest satırlar için boş bırakılabilir; açıklama alanı kullanılır.', null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün'),
        ),
        migrations.CreateModel(
            name='MusteriTeklifSartlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_sarti', models.TextField(blank=True, verbose_name='Ödeme şartı')),
                ('teslim_suresi', models.CharField(blank=True, max_length=200, verbose_name='Teslim süresi')),
                ('genel_notlar', models.TextField(blank=True, verbose_name='Genel notlar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('musteri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teklif_sartlari', to='stokapp.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri teklif şartları',
                'verbose_name_plural': 'Müşteri teklif şartları',
                'db_table': 'customer_offer_conditions',
            },
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teklif_no', models.CharField(max_length=50, unique=True, verbose_name='Teklif no')),
                ('ad', models.CharField(max_length=300, verbose_name='Teklif adı')),
                ('musteri_adi', models.CharField(blank=True, max_length=200, verbose_name='Müşteri adı (anlık)')),
                ('musteri_telefon', models.CharField(blank=True, max_length=40, verbose_name='Telefon (anlık)')),
                ('musteri_email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta (anlık)')),
                ('musteri_adres', models.TextField(blank=True, verbose_name='Adres (anlık)')),
                ('duzenleme_tarihi', models.DateField(verbose_name='Düzenleme tarihi')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade tarihi')),
                ('doviz_kuru', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='Döviz kuru')),
                ('sartlar_metni', models.TextField(blank=True, verbose_name='Teklif şartları')),
                ('durum', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('accepted', 'Kabul edildi'), ('rejected', 'Reddedildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('arsivlendi', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam tutar')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.musteri', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'db_table': 'offers',
                'ordering': ['-duzenleme_tarihi', '-id'],
            },
        ),
        migrations.AddField(
            model_name='siparis',
            name='kaynak_teklif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_siparisler', to='stokapp.teklif', verbose_name='Kaynak teklif'),
        ),
        migrations.CreateModel(
            name='TeklifKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('product', 'Stoktan ürün'), ('custom', 'Serbest kalem')], default='product', max_length=20, verbose_name='Tip')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('miktar', models.DecimalField(decimal_places=3, default=1, max_digits=14, verbose_name='Miktar')),
                ('birim', models.CharField(default='Adet', max_length=40, verbose_name='Birim')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Birim fiyat')),
                ('satir_toplam', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Satır toplamı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('stok_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün')),
                ('teklif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stokapp.teklif', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif kalemi',
                'verbose_name_plural': 'Teklif kalemleri',
                'db_table': 'offer_items',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
