# Generated by Django 5.2.7 on 2026-04-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stokapp", "0069_teklif_yonetimi_ve_siparis_kaynak"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonelBelgesi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("belge_adi", models.CharField(max_length=150, verbose_name="Belge Adı")),
                ("belge_no", models.CharField(blank=True, max_length=100, verbose_name="Belge No")),
                ("belge_dosyasi", models.FileField(blank=True, null=True, upload_to="personel_belgeler/%Y/%m/%d/", verbose_name="Belge Dosyası")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("yenileme_gerekli", models.BooleanField(default=False, verbose_name="Yenileme Gerekli mi?")),
                ("yenileme_tarihi", models.DateField(blank=True, null=True, verbose_name="Yenileme Tarihi")),
                ("hatirlatma_gun_once", models.PositiveIntegerField(blank=True, null=True, verbose_name="Yenileme Hatırlatma (Gün)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("personel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="belgeler", to="stokapp.personel", verbose_name="Personel")),
            ],
            options={
                "verbose_name": "Personel Belgesi",
                "verbose_name_plural": "Personel Belgeleri",
                "ordering": ["yenileme_tarihi", "-created_at"],
            },
        ),
    ]
