# Generated by Django 5.2.7 on 2026-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stokapp", "0070_personel_belgesi"),
    ]

    operations = [
        migrations.AddField(
            model_name="personelbelgesi",
            name="arsivlendi",
            field=models.BooleanField(default=False, verbose_name="Arşivlendi"),
        ),
    ]
