# Generated by Django 5.2.7 on 2026-04-30 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stokapp", "0071_personelbelgesi_arsivlendi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gayrimenkul",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ad", models.CharField(max_length=250, verbose_name="Gayrimenkul adı")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("ARSA", "Arsa"),
                            ("OFIS", "Ofis"),
                            ("DEPO", "Depo"),
                            ("FABRIKA", "Fabrika"),
                            ("DUKKAN", "Dükkan"),
                            ("KONUT", "Konut"),
                            ("DIGER", "Diğer"),
                        ],
                        default="OFIS",
                        max_length=20,
                        verbose_name="Gayrimenkul tipi",
                    ),
                ),
                (
                    "sahiplik_tipi",
                    models.CharField(
                        choices=[("SAHIP", "Sahip olunan"), ("KIRALIK", "Kiralık")],
                        default="SAHIP",
                        max_length=20,
                        verbose_name="Sahiplik tipi",
                    ),
                ),
                ("il", models.CharField(max_length=80, verbose_name="İl")),
                ("ilce", models.CharField(max_length=80, verbose_name="İlçe")),
                ("adres", models.TextField(verbose_name="Açık adres")),
                ("ada_parsel", models.CharField(blank=True, max_length=200, verbose_name="Ada / parsel")),
                ("tapu_no", models.CharField(blank=True, max_length=120, verbose_name="Tapu no")),
                (
                    "metrekare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Metrekare",
                    ),
                ),
                (
                    "kullanim_durumu",
                    models.CharField(
                        choices=[
                            ("AKTIF", "Aktif"),
                            ("PASIF", "Pasif"),
                            ("KIRADA", "Kirada"),
                            ("BOS", "Boş"),
                        ],
                        default="AKTIF",
                        max_length=20,
                        verbose_name="Kullanım durumu",
                    ),
                ),
                ("sorumlu_kisi", models.CharField(blank=True, max_length=200, verbose_name="Sorumlu kişi")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "alis_veya_kira_bedeli",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Alış bedeli veya kira bedeli",
                    ),
                ),
                ("para_birimi", models.CharField(default="TRY", max_length=3, verbose_name="Para birimi")),
                (
                    "kira_baslangic_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Kira başlangıç tarihi"),
                ),
                ("kira_bitis_tarihi", models.DateField(blank=True, null=True, verbose_name="Kira bitiş tarihi")),
                (
                    "yillik_emlak_vergisi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Yıllık emlak vergisi tutarı",
                    ),
                ),
                (
                    "vergi_odeme_periyodu",
                    models.CharField(
                        choices=[
                            ("YILLIK", "Yıllık"),
                            ("ALTI_AY", "6 aylık"),
                            ("UC_AY", "3 aylık"),
                        ],
                        default="YILLIK",
                        max_length=20,
                        verbose_name="Vergi ödeme periyodu",
                    ),
                ),
                ("sigorta_police_no", models.CharField(blank=True, max_length=120, verbose_name="Sigorta poliçe no")),
                ("sigorta_firmasi", models.CharField(blank=True, max_length=200, verbose_name="Sigorta firması")),
                (
                    "sigorta_baslangic_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Sigorta başlangıç tarihi"),
                ),
                ("sigorta_bitis_tarihi", models.DateField(blank=True, null=True, verbose_name="Sigorta bitiş tarihi")),
                (
                    "sigorta_tutari",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Sigorta tutarı",
                    ),
                ),
                (
                    "aidat_site_gideri",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Aidat / site gideri",
                    ),
                ),
                ("bakim_giderleri_notu", models.TextField(blank=True, verbose_name="Bakım giderleri notu")),
                ("yonetim_notlari", models.TextField(blank=True, verbose_name="Yönetim notları")),
                ("arsivlendi", models.BooleanField(default=False, verbose_name="Arşivlendi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gayrimenkul",
                "verbose_name_plural": "Gayrimenkuller",
                "ordering": ["il", "ilce", "ad"],
            },
        ),
        migrations.CreateModel(
            name="GayrimenkulIslemi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "islem_tipi",
                    models.CharField(
                        choices=[
                            ("EMLAK_VERGISI", "Emlak vergisi"),
                            ("SIGORTA", "Sigorta"),
                            ("KIRA", "Kira"),
                            ("AIDAT", "Aidat"),
                            ("BAKIM", "Bakım"),
                            ("ABONELIK", "Abonelik"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="İşlem tipi",
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "tutar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Tutar",
                    ),
                ),
                ("para_birimi", models.CharField(default="TRY", max_length=3, verbose_name="Para birimi")),
                ("vade_tarihi", models.DateField(verbose_name="Vade tarihi")),
                ("odeme_tarihi", models.DateField(blank=True, null=True, verbose_name="Ödeme tarihi")),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("BEKLIYOR", "Bekliyor"),
                            ("ODENDI", "Ödendi"),
                            ("GECIKTI", "Gecikti"),
                            ("IPTAL", "İptal"),
                        ],
                        default="BEKLIYOR",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        help_text="Poliçe, dekont, fatura vb.",
                        null=True,
                        upload_to="gayrimenkul_islem/%Y/%m/%d/",
                        verbose_name="Dosya eki",
                    ),
                ),
                (
                    "hatirlatma_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Hatırlatma tarihi"),
                ),
                ("not_metni", models.TextField(blank=True, verbose_name="Not")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gayrimenkul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="islemler",
                        to="stokapp.gayrimenkul",
                        verbose_name="Gayrimenkul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gayrimenkul işlemi",
                "verbose_name_plural": "Gayrimenkul işlemleri",
                "ordering": ["vade_tarihi", "id"],
            },
        ),
        migrations.CreateModel(
            name="GayrimenkulDosya",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("dosya", models.FileField(upload_to="gayrimenkul_dosya/%Y/%m/%d/", verbose_name="Dosya")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gayrimenkul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosyalar",
                        to="stokapp.gayrimenkul",
                        verbose_name="Gayrimenkul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gayrimenkul dosyası",
                "verbose_name_plural": "Gayrimenkul dosyaları",
                "ordering": ["-created_at"],
            },
        ),
    ]
