# Generated by Django 5.2.7 on 2026-05-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0076_remove_talepkalemi_stok_ve_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='kaynak_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_teklifler', to='stokapp.siparis', verbose_name='Kaynak sipariş'),
        ),
        migrations.AddField(
            model_name='teklifkalemi',
            name='vergi_yuzdesi',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Vergi %'),
        ),
        migrations.AlterField(
            model_name='teklifkalemi',
            name='stok_item',
            field=models.ForeignKey(blank=True, help_text='Serbest satırlar için boş bırakılabilir.', null=True, on_delete=django.db.models.deletion.PROTECT, to='stokapp.stokitem', verbose_name='Ürün'),
        ),
    ]
