# Generated by Django 5.2.7 on 2026-05-02 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0079_tedarikci_ilgili_kisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriKontrolFormSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_adi', models.CharField(max_length=200, verbose_name='Form adı')),
                ('form_kodu', models.SlugField(max_length=80, unique=True, verbose_name='Form kodu')),
                ('revizyon', models.CharField(default='A', max_length=20, verbose_name='Revizyon')),
                ('sablon_dosyasi', models.FileField(blank=True, help_text='Örn. BOŞ FORM.dotx — opsiyonel.', upload_to='kalite/kontrol_form_sablonlari/%Y/%m/', verbose_name='Şablon dosyası')),
                ('sablon_tipi', models.CharField(choices=[('WORD', 'Word (.dotx/docx)'), ('HTML', 'HTML şablon'), ('DIGER', 'Diğer')], default='HTML', max_length=10, verbose_name='Şablon tipi')),
                ('html_sablon', models.TextField(blank=True, help_text='Boş bırakılırsa sistem gövdesi (include) kullanılır.', verbose_name='HTML şablon (opsiyonel)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('musteri', models.ForeignKey(blank=True, help_text='Boş bırakılırsa şablon genel kullanım içindir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musteri_kontrol_form_sablonlari', to='stokapp.musteri', verbose_name='İlgili müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri kontrol form şablonu',
                'verbose_name_plural': 'Müşteri kontrol form şablonları',
                'ordering': ['form_adi'],
            },
        ),
        migrations.CreateModel(
            name='MusteriKontrolFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_adi', models.CharField(max_length=200, verbose_name='Form adı')),
                ('form_no', models.CharField(help_text='Benzersiz form numarası.', max_length=80, unique=True, verbose_name='Form no')),
                ('siparis_no', models.CharField(blank=True, max_length=80, verbose_name='Sipariş no')),
                ('uretim_emri_no', models.CharField(blank=True, max_length=80, verbose_name='Üretim emri no')),
                ('urun_kodu', models.CharField(blank=True, max_length=120, verbose_name='Ürün / parça kodu (SAP)')),
                ('urun_adi', models.CharField(blank=True, max_length=300, verbose_name='Ürün / parça adı')),
                ('miktar', models.CharField(blank=True, max_length=50, verbose_name='Adet')),
                ('parti_no', models.CharField(blank=True, max_length=80, verbose_name='Parti / lot no')),
                ('seri_no', models.CharField(blank=True, max_length=80, verbose_name='Seri no')),
                ('resim_numarasi', models.CharField(blank=True, max_length=120, verbose_name='Resim numarası')),
                ('dokuman_no', models.CharField(blank=True, max_length=80, verbose_name='Döküman no')),
                ('tedarikci_unvan', models.CharField(blank=True, max_length=400, verbose_name='Tedarikçi')),
                ('kontrol_tarihi', models.DateField(blank=True, null=True, verbose_name='Kontrol tarihi')),
                ('hazirlayan', models.CharField(blank=True, max_length=200, verbose_name='Hazırlayan')),
                ('kontrol_eden', models.CharField(blank=True, max_length=200, verbose_name='Kontrol eden')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('KONTROL_EDILIYOR', 'Kontrol Ediliyor'), ('TAMAMLANDI', 'Tamamlandı'), ('MUSTERIYE_GONDERILDI', 'Müşteriye Gönderildi'), ('REVIZE_EDILDI', 'Revize Edildi'), ('ARSIVLENDI', 'Arşivlendi')], default='TASLAK', max_length=30, verbose_name='Durum')),
                ('revizyon', models.CharField(default='A', max_length=20, verbose_name='Revizyon')),
                ('form_verisi_json', models.JSONField(blank=True, default=dict, help_text='Tablo ve ek alanların gövde verisi.', verbose_name='Form hücre verisi (JSON)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('arsivli', models.BooleanField(default=False, verbose_name='Arşivli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_musteri_kontrol_formlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musteri_kontrol_formlari', to='stokapp.musteri', verbose_name='Müşteri')),
                ('sablon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formlar', to='stokapp.musterikontrolformsablonu', verbose_name='Şablon')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelledigi_musteri_kontrol_formlari', to=settings.AUTH_USER_MODEL, verbose_name='Son güncelleyen')),
            ],
            options={
                'verbose_name': 'Müşteri ürün kontrol formu',
                'verbose_name_plural': 'Müşteri ürün kontrol formları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusteriKontrolFormGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=120, verbose_name='İşlem')),
                ('eski_durum', models.CharField(blank=True, max_length=30, verbose_name='Eski durum')),
                ('yeni_durum', models.CharField(blank=True, max_length=30, verbose_name='Yeni durum')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musteri_kontrol_form_gecmisi', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis_kayitlari', to='stokapp.musterikontrolformu', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Müşteri kontrol form geçmişi',
                'verbose_name_plural': 'Müşteri kontrol form geçmişi',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='MusteriKontrolFormDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='kalite/musteri_kontrol_formlari/%Y/%m/', verbose_name='Dosya')),
                ('dosya_tipi', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('DIGER', 'Diğer')], default='DIGER', max_length=10, verbose_name='Dosya tipi')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme tarihi')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='stokapp.musterikontrolformu', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Müşteri kontrol form dosyası',
                'verbose_name_plural': 'Müşteri kontrol form dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='musterikontrolformu',
            index=models.Index(fields=['-created_at'], name='stokapp_mus_created_40b315_idx'),
        ),
        migrations.AddIndex(
            model_name='musterikontrolformu',
            index=models.Index(fields=['form_no'], name='stokapp_mus_form_no_b9bc50_idx'),
        ),
        migrations.AddIndex(
            model_name='musterikontrolformu',
            index=models.Index(fields=['durum', 'arsivli'], name='stokapp_mus_durum_454c9f_idx'),
        ),
    ]
