# Generated by Django 5.2.7 on 2026-05-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0080_musteri_kontrol_formlari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifGonderimGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alicilar', models.JSONField(default=list, verbose_name='Alıcılar')),
                ('cc', models.JSONField(blank=True, default=list, verbose_name='CC')),
                ('bcc', models.JSONField(blank=True, default=list, verbose_name='BCC')),
                ('konu', models.CharField(max_length=400, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('pdf_dosyasi', models.FileField(blank=True, upload_to='teklif_gonderimleri/%Y/%m/', verbose_name='PDF dosyası')),
                ('gonderim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim tarihi')),
                ('durum', models.CharField(choices=[('GONDERILDI', 'Gönderildi'), ('HATA', 'Hata')], default='GONDERILDI', max_length=20, verbose_name='Durum')),
                ('hata_mesaji', models.TextField(blank=True, verbose_name='Hata mesajı')),
            ],
            options={
                'verbose_name': 'Teklif gönderim geçmişi',
                'verbose_name_plural': 'Teklif gönderim geçmişi',
                'ordering': ['-gonderim_tarihi'],
            },
        ),
        migrations.AddField(
            model_name='teklif',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_teklifler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='pdf_dosyasi',
            field=models.FileField(blank=True, upload_to='teklif_pdf/%Y/%m/', verbose_name='Son gönderilen PDF'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='red_notu',
            field=models.TextField(blank=True, verbose_name='Red notu'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='red_sebebi',
            field=models.CharField(blank=True, choices=[('FIYAT_YUKSEK', 'Fiyat yüksek bulundu'), ('TERMIN_UYGUN_DEGIL', 'Termin uygun değil'), ('RAKIP_TERCIH', 'Rakip firma tercih edildi'), ('TEKNIK_UYGUN_DEGIL', 'Teknik şartlar uygun değil'), ('PROJE_ERTELEDI', 'Müşteri projeyi erteledi'), ('PROJE_IPTAL', 'Müşteri projeyi iptal etti'), ('BUTCE_ONAY', 'Bütçe onayı alınamadı'), ('YANLIS_TEKLIF', 'Yanlış / gereksiz teklif'), ('DIGER', 'Diğer')], max_length=40, verbose_name='Red sebebi'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='red_sebebi_diger_aciklama',
            field=models.TextField(blank=True, verbose_name='Red — Diğer açıklama'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='red_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Red tarihi'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='reddeden_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reddettigi_teklifler', to=settings.AUTH_USER_MODEL, verbose_name='Reddeden kullanıcı'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='son_gonderim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son gönderim tarihi'),
        ),
        migrations.AddConstraint(
            model_name='siparis',
            constraint=models.UniqueConstraint(condition=models.Q(('kaynak_teklif__isnull', False)), fields=('kaynak_teklif',), name='siparis_unique_kaynak_teklif'),
        ),
        migrations.AddField(
            model_name='teklifgonderimgecmisi',
            name='gonderen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teklif_mail_gonderimleri', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
        migrations.AddField(
            model_name='teklifgonderimgecmisi',
            name='teklif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderim_gecmisi', to='stokapp.teklif', verbose_name='Teklif'),
        ),
    ]
