# Generated by Django 5.2.7 on 2026-05-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0081_teklif_pdf_mail_red_rapor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeklifSarti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('HAZIR', 'Hazır şablon'), ('OZEL', 'Özel şart')], max_length=10, verbose_name='Tip')),
                ('sablon_kodu', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Şablon kodu')),
                ('baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('degerler_json', models.JSONField(default=dict, verbose_name='Parametreler')),
                ('metin', models.TextField(blank=True, verbose_name='Üretilen metin')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('teklif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sart_kayitlari', to='stokapp.teklif', verbose_name='Teklif')),
            ],
            options={
                'verbose_name': 'Teklif şartı',
                'verbose_name_plural': 'Teklif şartları',
                'db_table': 'offer_terms_lines',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
