# Generated by Django 5.2.7 on 2026-05-02 13:47

from django.db import migrations, models


def forwards_teklif_para_normalize_and_kalem_backfill(apps, schema_editor):
    Teklif = apps.get_model('stokapp', 'Teklif')
    TeklifKalemi = apps.get_model('stokapp', 'TeklifKalemi')
    valid = {'TL', 'USD', 'EUR', 'GBP'}
    Teklif.objects.filter(para_birimi='TRY').update(para_birimi='TL')
    for k in TeklifKalemi.objects.iterator():
        tp = (
            Teklif.objects.filter(pk=k.teklif_id).values_list('para_birimi', flat=True).first()
            or 'TL'
        )
        pb = (tp or 'TL').strip()
        if pb == 'TRY':
            pb = 'TL'
        if pb == 'MIX' or pb not in valid:
            pb = 'TL'
        if k.para_birimi != pb:
            k.para_birimi = pb
            k.save(update_fields=['para_birimi'])


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0082_teklif_sarti'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklifkalemi',
            name='para_birimi',
            field=models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3, verbose_name='Para birimi'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='ad',
            field=models.CharField(blank=True, max_length=300, verbose_name='Teklif adı'),
        ),
        migrations.RunPython(
            forwards_teklif_para_normalize_and_kalem_backfill,
            migrations.RunPython.noop,
        ),
    ]
