# Generated by Django 5.2.7 on 2026-05-02 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0084_teklif_kalem_notu_banka_pb_gecerlilik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('slug', models.SlugField(unique=True, verbose_name='Kod')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'db_table': 'rbac_rol',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SistemYetkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=120, unique=True, verbose_name='Kod')),
                ('ad', models.CharField(max_length=200, verbose_name='Ad')),
                ('modul', models.CharField(db_index=True, max_length=80, verbose_name='Modül')),
            ],
            options={
                'verbose_name': 'Yetki',
                'verbose_name_plural': 'Yetkiler',
                'db_table': 'rbac_sistem_yetkisi',
                'ordering': ['modul', 'kod'],
            },
        ),
        migrations.CreateModel(
            name='KullaniciRolu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tekos_rolleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='stokapp.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Kullanıcı rolü',
                'verbose_name_plural': 'Kullanıcı rolleri',
                'db_table': 'rbac_kullanici_rolu',
                'unique_together': {('user', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='RolYetkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkiler', to='stokapp.rol', verbose_name='Rol')),
                ('yetki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_baglantilari', to='stokapp.sistemyetkisi', verbose_name='Yetki')),
            ],
            options={
                'verbose_name': 'Rol yetkisi',
                'verbose_name_plural': 'Rol yetkileri',
                'db_table': 'rbac_rol_yetkisi',
                'unique_together': {('rol', 'yetki')},
            },
        ),
    ]
