# Generated by Django 5.2.7 on 2026-05-04 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0086_rbac_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArGeProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_kodu', models.CharField(max_length=40, unique=True, verbose_name='Proje kodu')),
                ('proje_adi', models.CharField(max_length=200, verbose_name='Proje adı')),
                ('durum', models.CharField(choices=[('FIKIR', 'Fikir'), ('TASARIMDA', 'Tasarımda'), ('PROTOTIP', 'Prototip'), ('DEMO_URETIM', 'Demo Üretim'), ('TEST', 'Test'), ('REVIZYON', 'Revizyon'), ('ONAYLANDI', 'Onaylandı'), ('SERI_URETIME_HAZIR', 'Seri Üretime Hazır'), ('IPTAL', 'İptal')], default='FIKIR', max_length=30, verbose_name='Durum')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç tarihi')),
                ('hedef_tarih', models.DateField(blank=True, null=True, verbose_name='Hedef tarih')),
                ('oncelik', models.CharField(choices=[('DUSUK', 'Düşük'), ('NORMAL', 'Normal'), ('YUKSEK', 'Yüksek'), ('ACIL', 'Acil')], default='NORMAL', max_length=10, verbose_name='Öncelik')),
                ('hedef_maliyet', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Hedef maliyet')),
                ('hedef_satis_fiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Hedef satış fiyatı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('arsivli', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('teknik_resim_hazir', models.BooleanField(default=False, verbose_name='Teknik resim hazır')),
                ('cad_hazir', models.BooleanField(default=False, verbose_name='CAD hazır')),
                ('malzeme_tanimli', models.BooleanField(default=False, verbose_name='Malzeme tanımlı')),
                ('operasyon_tanimli', models.BooleanField(default=False, verbose_name='Operasyon tanımlı')),
                ('maliyet_hesaplandi', models.BooleanField(default=False, verbose_name='Maliyet hesaplandı')),
                ('kontrol_plani_hazir', models.BooleanField(default=False, verbose_name='Kontrol planı hazır')),
                ('paketleme_hazir', models.BooleanField(default=False, verbose_name='Paketleme hazır')),
                ('stok_kodu_var', models.BooleanField(default=False, verbose_name='Stok kodu var')),
                ('satis_fiyati_belirlendi', models.BooleanField(default=False, verbose_name='Satış fiyatı belirlendi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('sorumlu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arge_projeleri_sorumlu', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arge_projeleri', to='stokapp.stokitem', verbose_name='Stok ürünü')),
            ],
            options={
                'verbose_name': 'Ar-Ge projesi',
                'verbose_name_plural': 'Ar-Ge projeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArGeDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='arge/dosya/%Y/%m/', verbose_name='Dosya')),
                ('dosya_tipi', models.CharField(choices=[('TASARIM', 'Tasarım'), ('TEKNIK_RESIM', 'Teknik resim'), ('PROTOTIP', 'Prototip'), ('TEST', 'Test'), ('MALIYET', 'Maliyet'), ('KALITE', 'Kalite'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Dosya tipi')),
                ('aciklama', models.CharField(blank=True, max_length=500, verbose_name='Açıklama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='stokapp.argeproje', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Ar-Ge dosyası',
                'verbose_name_plural': 'Ar-Ge dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArGeRevizyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revizyon_no', models.CharField(help_text='Örn: R0, R1', max_length=12, verbose_name='Revizyon no')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('revizyon_nedeni', models.CharField(max_length=300, verbose_name='Revizyon nedeni')),
                ('degisiklik_tipi', models.CharField(choices=[('TASARIM', 'Tasarım'), ('MALZEME', 'Malzeme'), ('OLCU', 'Ölçü'), ('URETIM', 'Üretim'), ('MONTAJ', 'Montaj'), ('MALIYET', 'Maliyet'), ('KALITE', 'Kalite'), ('TEST', 'Test'), ('MUSTERI', 'Müşteri'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Değişiklik tipi')),
                ('onceki_durum', models.CharField(blank=True, choices=[('FIKIR', 'Fikir'), ('TASARIMDA', 'Tasarımda'), ('PROTOTIP', 'Prototip'), ('DEMO_URETIM', 'Demo Üretim'), ('TEST', 'Test'), ('REVIZYON', 'Revizyon'), ('ONAYLANDI', 'Onaylandı'), ('SERI_URETIME_HAZIR', 'Seri Üretime Hazır'), ('IPTAL', 'İptal')], max_length=30, verbose_name='Önceki durum')),
                ('yeni_durum', models.CharField(blank=True, choices=[('FIKIR', 'Fikir'), ('TASARIMDA', 'Tasarımda'), ('PROTOTIP', 'Prototip'), ('DEMO_URETIM', 'Demo Üretim'), ('TEST', 'Test'), ('REVIZYON', 'Revizyon'), ('ONAYLANDI', 'Onaylandı'), ('SERI_URETIME_HAZIR', 'Seri Üretime Hazır'), ('IPTAL', 'İptal')], max_length=30, verbose_name='Yeni durum')),
                ('karar', models.CharField(choices=[('KABUL', 'Kabul'), ('RED', 'Red'), ('BEKLEME', 'Beklemede')], default='BEKLEME', max_length=12, verbose_name='Karar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='arge/revizyon/%Y/%m/', verbose_name='Dosya')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='arge/revizyon/img/%Y/%m/', verbose_name='Görsel')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revizyonlar', to='stokapp.argeproje', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Ar-Ge revizyonu',
                'verbose_name_plural': 'Ar-Ge revizyonları',
                'ordering': ['proje', 'revizyon_no'],
            },
        ),
        migrations.AddIndex(
            model_name='argeproje',
            index=models.Index(fields=['durum'], name='stokapp_arg_durum_448c10_idx'),
        ),
        migrations.AddIndex(
            model_name='argeproje',
            index=models.Index(fields=['arsivli', '-created_at'], name='stokapp_arg_arsivli_148fea_idx'),
        ),
        migrations.AddIndex(
            model_name='argeproje',
            index=models.Index(fields=['stok_item'], name='stokapp_arg_stok_it_9916ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='argerevizyon',
            unique_together={('proje', 'revizyon_no')},
        ),
    ]
