# Generated by Django 5.2.7 on 2026-05-06 18:51

import django.db.models.deletion
import stokapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0089_approval_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TedarikciTeklifKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_fiyat', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Birim Fiyat')),
                ('para_birimi', models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('teslim_suresi_gun', models.IntegerField(blank=True, null=True, verbose_name='Teslim Süresi (gün)')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('secildi', models.BooleanField(default=False, verbose_name='Kazanan Teklif')),
                ('girildi_mi', models.BooleanField(default=False, verbose_name='Girildi mi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tedarikçi Teklif Kalemi',
                'verbose_name_plural': 'Tedarikçi Teklif Kalemleri',
                'ordering': ['rfq_kalemi__sira', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, help_text='Bu tedarikçinin tedarik ettiği kategori etiketleri. RFQ önerilerinde kullanılır.', related_name='tedarikciler', to='stokapp.kategori', verbose_name='Etiketler / Kategoriler'),
        ),
        migrations.AddField(
            model_name='tedarikci',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='teklif_banka_hesap_ids',
            field=models.JSONField(blank=True, default=stokapp.models._default_teklif_banka_ids, help_text='PDF/teklif özeti için sıralı banka hesabı pk listesi.', verbose_name='Seçili banka hesabı kimlikleri'),
        ),
        migrations.AddField(
            model_name='satinalmakalemi',
            name='kaynak_teklif_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donusen_satinalma_kalemleri', to='stokapp.tedarikciteklifkalemi', verbose_name='Kaynak Tedarikçi Teklifi'),
        ),
        migrations.CreateModel(
            name='TeklifTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(editable=False, max_length=40, unique=True, verbose_name='RFQ No')),
                ('baslik', models.CharField(max_length=300, verbose_name='Başlık')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('TEKLIF_BEKLENIYOR', 'Teklif Bekleniyor'), ('DEGERLENDIRMEDE', 'Değerlendirmede'), ('SIPARISE_DONUSTURULDU', 'Siparişe Dönüştürüldü'), ('IPTAL', 'İptal')], default='TASLAK', max_length=30, verbose_name='Durum')),
                ('oncelik', models.CharField(choices=[('FIYAT', 'Fiyat'), ('TERMIN', 'Termin')], default='FIYAT', max_length=10, verbose_name='Öncelik')),
                ('olusturma_tarihi', models.DateField(verbose_name='Oluşturma Tarihi')),
                ('son_teklif_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Teklif Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Varsayılan Para Birimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaynak_talep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqlar', to='stokapp.talep', verbose_name='Kaynak Talep')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_rfqlar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Teklif Talebi (RFQ)',
                'verbose_name_plural': 'Teklif Talepleri (RFQ)',
                'ordering': ['-olusturma_tarihi', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TeklifTalebiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalem_adi', models.CharField(max_length=300, verbose_name='Kalem Adı')),
                ('miktar', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Miktar')),
                ('birim', models.CharField(default='Adet', max_length=20, verbose_name='Birim')),
                ('teknik_notlar', models.TextField(blank=True, verbose_name='Teknik Notlar')),
                ('istenen_termin', models.DateField(blank=True, null=True, verbose_name='İstenen Termin')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stokapp.tekliftalebi', verbose_name='RFQ')),
                ('stok_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_kalemleri', to='stokapp.stokitem', verbose_name='Stok')),
            ],
            options={
                'verbose_name': 'RFQ Kalemi',
                'verbose_name_plural': 'RFQ Kalemleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tedarikciteklifkalemi',
            name='rfq_kalemi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tedarikci_teklifleri', to='stokapp.tekliftalebikalemi', verbose_name='RFQ Kalemi'),
        ),
        migrations.AddField(
            model_name='satinalmakalemi',
            name='kaynak_rfq_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donusen_satinalma_kalemleri', to='stokapp.tekliftalebikalemi', verbose_name='Kaynak RFQ Kalemi'),
        ),
        migrations.CreateModel(
            name='TeklifTalebiTedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harici_ad', models.CharField(blank=True, max_length=200, verbose_name='Harici Firma Adı')),
                ('harici_email', models.EmailField(blank=True, max_length=254, verbose_name='Harici E-posta')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Teklif Bekleniyor'), ('TEKLIF_GIRDI', 'Teklif Girdi'), ('IPTAL', 'İptal')], default='BEKLIYOR', max_length=20, verbose_name='Durum')),
                ('gonderim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Mail Gönderim Tarihi')),
                ('mail_gonderildi', models.BooleanField(default=False, verbose_name='Mail Gönderildi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tedarikci_baglantilari', to='stokapp.tekliftalebi', verbose_name='RFQ')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_baglantilari', to='stokapp.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'RFQ Tedarikçisi',
                'verbose_name_plural': 'RFQ Tedarikçileri',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tedarikciteklifkalemi',
            name='rfq_tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalem_teklifleri', to='stokapp.tekliftalebitedarikci', verbose_name='RFQ Tedarikçisi'),
        ),
        migrations.AddConstraint(
            model_name='tekliftalebitedarikci',
            constraint=models.UniqueConstraint(condition=models.Q(('tedarikci__isnull', False)), fields=('rfq', 'tedarikci'), name='uniq_rfq_tedarikci'),
        ),
        migrations.AlterUniqueTogether(
            name='tedarikciteklifkalemi',
            unique_together={('rfq_tedarikci', 'rfq_kalemi')},
        ),
    ]
