# Generated by Django 5.2.7 on 2026-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0090_tedarikciteklifkalemi_tedarikci_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayarlar',
            name='tekora_aktif',
            field=models.BooleanField(default=True, help_text='Kapalıysa TEKORA IMAP mail takibi durur.', verbose_name='TEKORA Aktif'),
        ),
    ]
