# Generated by Django 5.2.7 on 2026-05-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0091_genelayarlar_tekora_aktif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StokSayimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('durum', models.CharField(choices=[('DEVAM', 'Devam ediyor'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal')], default='DEVAM', max_length=15, verbose_name='Durum')),
                ('sadece_stok_takip', models.BooleanField(default=True, verbose_name='Sadece stok takibi açık ürünler')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tamamlanma_zamani', models.DateTimeField(blank=True, null=True)),
                ('depo', models.ForeignKey(blank=True, help_text='Boşsa tüm depolar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stokapp.depo', verbose_name='Depo filtresi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_sayimlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Stok sayımı',
                'verbose_name_plural': 'Stok sayımları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StokSayimiKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('sistem_miktar_snapshot', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Sayım başında sistem miktarı')),
                ('sayilan_miktar', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Sayılan miktar')),
                ('fark_miktar', models.DecimalField(blank=True, decimal_places=3, help_text='Hareket oluşturulduğunda işaretli fark.', max_digits=14, null=True, verbose_name='Uygulanan fark')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('SAYILDI', 'Sayıldı'), ('ATLANDI', 'Atlandı')], default='BEKLIYOR', max_length=15, verbose_name='Durum')),
                ('notlar', models.CharField(blank=True, max_length=500)),
                ('hareket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sayim_kalemi', to='stokapp.stokhareketi', verbose_name='Sayım hareketi')),
                ('sayim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='stokapp.stoksayimi')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sayim_kalemleri', to='stokapp.stokitem')),
            ],
            options={
                'verbose_name': 'Stok sayım kalemi',
                'verbose_name_plural': 'Stok sayım kalemleri',
                'ordering': ['sayim_id', 'sira', 'id'],
                'indexes': [models.Index(fields=['sayim', 'durum', 'sira'], name='stokapp_sto_sayim_i_a7531d_idx')],
            },
        ),
    ]
