# Generated by Django 5.2.7 on 2026-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0092_stok_sayimi_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurulumdosyasi',
            name='pdf_dosya',
            field=models.FileField(blank=True, null=True, upload_to='kurulum_dosyalari/%Y/%m/%d/', verbose_name='PDF Dosyası'),
        ),
    ]
