# Generated by Django 5.2.7 on 2026-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0093_alter_kurulumdosyasi_pdf_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncprogram',
            name='urun_parcasi',
            field=models.CharField(blank=True, default='', help_text='Programın yapıldığı reçete bileşeni (örn: Alt Plaka, Üst Plaka)', max_length=200, verbose_name='Ürün Parçası'),
        ),
    ]
