# Generated by Django 5.2.7 on 2026-05-09 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0094_cncprogram_urun_parcasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CncDosyaAgaciKlasor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klasör Adı')),
                ('machine_type', models.CharField(choices=[('cnc_lathe', 'CNC Torna'), ('cnc_mill', 'CNC Freze')], max_length=20, verbose_name='Makine Tipi')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('aciklama', models.CharField(blank=True, default='', max_length=500, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_dosya_agaci_klasorleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stokapp.cncdosyaagaciklasor', verbose_name='Üst Klasör')),
            ],
            options={
                'verbose_name': 'CNC Dosya Ağacı Klasörü',
                'verbose_name_plural': 'CNC Dosya Ağacı Klasörleri',
                'ordering': ['sira', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cncprogram',
            name='dosya_konumu',
            field=models.ForeignKey(blank=True, help_text='Hafıza kartı / makine hafızasındaki klasör konumu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnc_programlar', to='stokapp.cncdosyaagaciklasor', verbose_name='Dosya Konumu'),
        ),
        migrations.AddIndex(
            model_name='cncdosyaagaciklasor',
            index=models.Index(fields=['machine_type', 'parent'], name='stokapp_cnc_machine_5affce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cncdosyaagaciklasor',
            unique_together={('parent', 'name', 'machine_type')},
        ),
    ]
