# Generated by Django 5.2.7 on 2026-05-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0096_cncekipman'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cncekipman',
            new_name='stokapp_cnc_machine_c96934_idx',
            old_name='stokapp_cnc_machine_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='cncekipman',
            new_name='stokapp_cnc_aktif_b52ad4_idx',
            old_name='stokapp_cnc_aktif_sira_idx',
        ),
        migrations.AddField(
            model_name='cncekipman',
            name='barkod_envanter_no',
            field=models.CharField(blank=True, default='', help_text='Barkod okuma veya depo envanter numarası (opsiyonel).', max_length=128, verbose_name='Barkod / envanter no'),
        ),
        migrations.AddField(
            model_name='cncekipman',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='cnc_ekipman/foto/%Y/%m/', verbose_name='Fotoğraf'),
        ),
        migrations.AddField(
            model_name='cncekipman',
            name='talimat_kurulum_satirlari',
            field=models.ManyToManyField(blank=True, help_text='Reçete talimatında bu ekipmanın geçtiği kurulum dosyası satırları (çoklu seçim, opsiyonel).', related_name='cnc_ekipmanlari', to='stokapp.recetetalimatkurulumdosyasi', verbose_name='Kurulum talimatı satırları'),
        ),
        migrations.AddField(
            model_name='cncekipman',
            name='teknik_pdf',
            field=models.FileField(blank=True, help_text='Opsiyonel teknik çizim veya talimat PDF’i.', null=True, upload_to='cnc_ekipman/pdf/%Y/%m/', verbose_name='Teknik PDF'),
        ),
    ]
