# Generated by Django 5.2.7 on 2026-05-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0097_cncekipman_foto_pdf_barkod_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cncekipman',
            name='talimat_kurulum_satirlari',
        ),
    ]
