# Generated by Django 5.2.7 on 2026-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0099_istasyon_cnc_grubu_kurulum_cnc_ekipman_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='action_type',
            field=models.CharField(choices=[('create_sales_order', 'Satış siparişi oluştur'), ('create_purchase_request', 'Satınalma talebi oluştur'), ('bulk_create_purchase_request', 'Toplu satınalma talebi oluştur'), ('send_supplier_quote_request', 'Tedarikçiye teklif talebi gönder'), ('approve_supplier_offer', 'Tedarikçi teklifini onayla'), ('create_purchase_order', 'Satınalma siparişi oluştur'), ('create_production_order', 'Üretim emri oluştur'), ('plan_payment', 'Ödeme planla'), ('send_customer_email', 'Müşteriye e-posta gönder')], max_length=100),
        ),
    ]
