# Generated by Django 5.2.7 on 2026-05-11 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0100_approval_bulk_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TekoraMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(max_length=80, verbose_name='Hafıza tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='Kaynak')),
                ('importance', models.IntegerField(default=1, verbose_name='Önem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Meta veri')),
            ],
            options={
                'verbose_name': 'TEKORA hafıza',
                'verbose_name_plural': 'TEKORA hafızalar',
                'db_table': 'tekora_memories',
                'ordering': ['-importance', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TekoraChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='Kullanıcı mesajı')),
                ('ai_response', models.TextField(blank=True, default='', verbose_name='AI yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('source', models.CharField(default='web_chat', max_length=40, verbose_name='Kaynak')),
                ('session_key', models.CharField(blank=True, default='', max_length=80, verbose_name='Oturum anahtarı')),
                ('raw_context', models.JSONField(blank=True, default=dict, verbose_name='Ham bağlam (ERP / araç özeti)')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata mesajı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekora_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'TEKORA sohbet logu',
                'verbose_name_plural': 'TEKORA sohbet logları',
                'db_table': 'tekora_chat_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TekoraDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(max_length=80, verbose_name='Karar tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Ek veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('status', models.CharField(default='recorded', max_length=40, verbose_name='Durum')),
                ('related_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekora_decision_logs', to='stokapp.approvalrequest', verbose_name='İlişkili onay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekora_decision_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'TEKORA karar logu',
                'verbose_name_plural': 'TEKORA karar logları',
                'db_table': 'tekora_decision_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TekoraToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120, verbose_name='Tool adı')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Sonuç')),
                ('dangerous', models.BooleanField(default=False, verbose_name='Tehlikeli')),
                ('approval_required', models.BooleanField(default=False, verbose_name='Onay gerekli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata mesajı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekora_tool_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'TEKORA tool logu',
                'verbose_name_plural': 'TEKORA tool logları',
                'db_table': 'tekora_tool_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
