# Generated by Django 5.2.7 on 2026-05-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0101_tekora_ai_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TekoraAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=80, verbose_name='Uyarı tipi')),
                ('severity', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Önem')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Ek veri')),
                ('source', models.CharField(default='tekora_alert_engine', max_length=80, verbose_name='Kaynak')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme zamanı')),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='İlişkili nesne ID')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=120, verbose_name='İlişkili nesne tipi')),
            ],
            options={
                'verbose_name': 'TEKORA uyarısı',
                'verbose_name_plural': 'TEKORA uyarıları',
                'db_table': 'tekora_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'related_object_type', 'related_object_id', 'created_at'], name='tekora_aler_alert_t_95d67c_idx'), models.Index(fields=['is_resolved', 'created_at'], name='tekora_aler_is_reso_1ab996_idx')],
            },
        ),
    ]
