# Generated by Django 5.2.7 on 2026-05-11 19:15

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0102_enable_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='TekoraMemoryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, default='chat_log', max_length=50, verbose_name='Kaynak tipi')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Kaynak ID')),
                ('text', models.TextField(verbose_name='Metin')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='Embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Meta veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('chat_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='stokapp.tekorachatlog', verbose_name='Chat log')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='stokapp.tekoramemory', verbose_name='Memory')),
            ],
            options={
                'verbose_name': 'TEKORA Memory Embedding',
                'verbose_name_plural': 'TEKORA Memory Embeddings',
                'db_table': 'tekora_memory_embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'created_at'], name='tekora_memo_source__4cd0c1_idx')],
            },
        ),
    ]
