# Generated by Django 5.2.7 on 2026-05-14 12:13

import django.db.models.deletion
from django.db import migrations, models


def seed_dis_operasyon_tipleri(apps, schema_editor):
    T = apps.get_model('stokapp', 'DisOperasyonTipi')
    seeds = [
        ('Lazer Kesim', 'lazer_kesim', 'DIS'),
        ('Galvaniz', 'galvaniz', 'DIS'),
        ('Boya', 'boya', 'DIS'),
        ('Kauçuk Kaplama', 'kaucuk_kaplama', 'DIS'),
        ('Isıl İşlem', 'isil_islem', 'DIS'),
        ('Taşlama', 'taslama', 'DIS'),
        ('Kaplama', 'kaplama', 'DIS'),
        ('Dış İşçilik', 'dis_iscilik', 'DIS'),
        ('Diğer', 'diger', 'DIS'),
        ('Kılavuz Çekme', 'kilavuz_cekme', 'IC'),
    ]
    for ad, kod, tip in seeds:
        T.objects.get_or_create(
            operasyon_kodu=kod,
            defaults={'ad': ad, 'ic_dis_tipi': tip, 'aktif': True},
        )


def seed_dis_operasyon_tipleri_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0104_uretimemri_ust_emir_alt_otomatik'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisOperasyonTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ad')),
                ('operasyon_kodu', models.SlugField(max_length=64, unique=True, verbose_name='Operasyon kodu')),
                ('ic_dis_tipi', models.CharField(choices=[('IC', 'İç Operasyon'), ('DIS', 'Dış Operasyon')], default='DIS', max_length=3, verbose_name='İç / Dış')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Operasyon Tipi',
                'verbose_name_plural': 'Operasyon Tipleri',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='stokitem',
            name='dis_operasyonda_miktar',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Şirket dışı operasyonda / tedarikçide bekleyen miktar (depo dışı takip).', max_digits=14, verbose_name='Dış operasyonda (tedarikçide)'),
        ),
        migrations.AlterField(
            model_name='stokhareketi',
            name='hareket_tipi',
            field=models.CharField(choices=[('GIRIS', 'Stok Girişi'), ('CIKIS', 'Stok Çıkışı'), ('SATIS_STOK', 'Stoktan Satış Çıkışı'), ('TRANSFER', 'Depo Transferi'), ('SAYIM', 'Sayım Düzeltmesi'), ('URETIM_GIRIS', 'Üretim Girişi'), ('URETIM_CIKIS', 'Üretim Çıkışı'), ('DISOP_GONDERIM', 'Dış Operasyon Gönderim'), ('DISOP_DONUS', 'Dış Operasyon Dönüş'), ('DISOP_FIRE', 'Dış Operasyon Fire'), ('DISOP_RED', 'Dış Operasyon Red / Hurda'), ('DISOP_EKSIK', 'Dış Operasyon Eksik'), ('DISOP_TESLIM_KALITE', 'Dış Operasyon Teslim (Kalite Bekliyor)'), ('DISOP_QC_KABUL', 'Dış Operasyon Kalite Kabul (Stoğa)')], max_length=22),
        ),
        migrations.CreateModel(
            name='DisOperasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operasyon_no', models.CharField(max_length=40, unique=True)),
                ('parti_no', models.CharField(blank=True, max_length=120, verbose_name='Parti / Lot No')),
                ('dis_operasyon_lokasyonu', models.CharField(blank=True, max_length=255, verbose_name='Dış operasyon lokasyonu / tedarikçi deposu')),
                ('gonderilen_miktar', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Gönderilen miktar')),
                ('birim', models.CharField(default='Adet', max_length=20, verbose_name='Birim')),
                ('gonderim_tarihi', models.DateField(verbose_name='Gönderim tarihi')),
                ('beklenen_donus_tarihi', models.DateField(blank=True, null=True, verbose_name='Beklenen dönüş tarihi')),
                ('birim_fiyat', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Birim işlem fiyatı')),
                ('para_birimi', models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3, verbose_name='Para birimi')),
                ('tahmini_toplam_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tahmini toplam maliyet')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('GONDERILDI', 'Gönderildi'), ('TEDARIKCIDE', 'Tedarikçide / İşlemde'), ('KISMI_DONUS', 'Kısmi Dönüş'), ('TAMAMLANDI', 'Tamamlandı'), ('KALITE_BEKLIYOR', 'Kalite Kontrol Bekliyor'), ('REDDEDILDI', 'Reddedildi'), ('IPTAL', 'İptal Edildi'), ('ARSIV', 'Arşivlendi')], default='TASLAK', max_length=20, verbose_name='Durum')),
                ('kalite_durumu', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('KABUL', 'Kabul'), ('SARTLI_KABUL', 'Şartlı Kabul'), ('RED', 'Red')], default='BEKLIYOR', max_length=16, verbose_name='Kalite durumu')),
                ('miktar_tedarikcide_kalan', models.DecimalField(decimal_places=3, default=0, help_text='Bu emir için henüz kapatılmamış (dönüş/fire/eksik ile düşülür).', max_digits=14, verbose_name='Tedarikçide kalan miktar')),
                ('miktar_kalite_bekliyor', models.DecimalField(decimal_places=3, default=0, help_text='Depoya alınmayı bekleyen dönen miktar.', max_digits=14, verbose_name='Kalite bekleyen miktar')),
                ('toplam_donen_miktar', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Toplam dönen (kabul öncesi)')),
                ('toplam_fire_miktar', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Toplam fire')),
                ('toplam_eksik_miktar', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Toplam eksik')),
                ('toplam_gerceklesen_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam gerçekleşen maliyet')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sevk_evrak_no', models.CharField(blank=True, max_length=120, verbose_name='Sevk evrak / irsaliye no')),
                ('arsivli', models.BooleanField(default=False, verbose_name='Arşivli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gonderim_deposu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dis_operasyon_gonderimleri', to='stokapp.depo', verbose_name='Gönderim deposu')),
                ('stok_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dis_operasyonlari', to='stokapp.stokitem', verbose_name='Stok ürünü')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dis_operasyonlar', to='stokapp.tedarikci', verbose_name='Tedarikçi')),
                ('uretim_emri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dis_operasyonlari', to='stokapp.uretimemri', verbose_name='Üretim emri')),
                ('operasyon_tipi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dis_operasyonlar', to='stokapp.disoperasyontipi', verbose_name='Operasyon tipi')),
            ],
            options={
                'verbose_name': 'Dış Operasyon',
                'verbose_name_plural': 'Dış Operasyonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stokhareketi',
            name='dis_operasyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_hareketleri', to='stokapp.disoperasyon', verbose_name='Dış operasyon'),
        ),
        migrations.CreateModel(
            name='DisOperasyonDonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donus_tarihi', models.DateField(verbose_name='Dönüş tarihi')),
                ('donen_miktar', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Dönen miktar')),
                ('fire_miktari', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Fire miktarı')),
                ('eksik_miktari', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Eksik miktar')),
                ('gerceklesen_birim_fiyat', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Gerçekleşen birim fiyat')),
                ('nakliye_maliyeti', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Nakliye maliyeti')),
                ('ek_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ek maliyet')),
                ('toplam_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam işlem maliyeti')),
                ('kalite_kontrol_gerekli', models.BooleanField(default=False, verbose_name='Kalite kontrol gerekli')),
                ('kalite_islenildi', models.BooleanField(default=False, verbose_name='Kalite işlendi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dis_operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donuslar', to='stokapp.disoperasyon', verbose_name='Dış operasyon')),
            ],
            options={
                'verbose_name': 'Dış Operasyon Dönüşü',
                'verbose_name_plural': 'Dış Operasyon Dönüşleri',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisOperasyonDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='dis_operasyon/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_tipi', models.CharField(choices=[('GENEL', 'Genel'), ('GONDERIM', 'Gönderim'), ('DONUS', 'Dönüş'), ('KALITE', 'Kalite')], default='GENEL', max_length=16, verbose_name='Dosya tipi')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dis_operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='stokapp.disoperasyon', verbose_name='Dış operasyon')),
            ],
            options={
                'verbose_name': 'Dış Operasyon Dosyası',
                'verbose_name_plural': 'Dış Operasyon Dosyaları',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DisOperasyonKaliteKontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol_tarihi', models.DateField(verbose_name='Kontrol tarihi')),
                ('kontrol_eden', models.CharField(max_length=200, verbose_name='Kontrol eden')),
                ('sonuc', models.CharField(choices=[('KABUL', 'Kabul'), ('SARTLI_KABUL', 'Şartlı Kabul'), ('RED', 'Red')], max_length=16, verbose_name='Sonuç')),
                ('kabul_miktari', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Kabul edilen miktar')),
                ('red_miktari', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Reddedilen miktar')),
                ('sartli_kabul_notu', models.TextField(blank=True, verbose_name='Şartlı kabul notu')),
                ('red_nedeni', models.TextField(blank=True, verbose_name='Red nedeni')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dis_operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalite_kayitlari', to='stokapp.disoperasyon', verbose_name='Dış operasyon')),
                ('donus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kalite_kayitlari', to='stokapp.disoperasyondonus', verbose_name='İlgili dönüş')),
            ],
            options={
                'verbose_name': 'Dış Operasyon Kalite Kontrolü',
                'verbose_name_plural': 'Dış Operasyon Kalite Kontrolleri',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisOperasyonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=80, verbose_name='İşlem')),
                ('eski_durum', models.CharField(blank=True, max_length=20, verbose_name='Eski durum')),
                ('yeni_durum', models.CharField(blank=True, max_length=20, verbose_name='Yeni durum')),
                ('kullanici', models.CharField(blank=True, max_length=120, verbose_name='Kullanıcı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dis_operasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loglar', to='stokapp.disoperasyon', verbose_name='Dış operasyon')),
            ],
            options={
                'verbose_name': 'Dış Operasyon Log',
                'verbose_name_plural': 'Dış Operasyon Logları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='disoperasyon',
            index=models.Index(fields=['durum', 'arsivli'], name='stokapp_dis_durum_bbda3a_idx'),
        ),
        migrations.AddIndex(
            model_name='disoperasyon',
            index=models.Index(fields=['tedarikci', 'durum'], name='stokapp_dis_tedarik_a7f2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='disoperasyon',
            index=models.Index(fields=['stok_item', 'durum'], name='stokapp_dis_stok_it_105976_idx'),
        ),
        migrations.RunPython(seed_dis_operasyon_tipleri, seed_dis_operasyon_tipleri_reverse),
    ]
