# Generated by Django 5.2.7 on 2026-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0107_uretim_rol_dis_operasyon_yetkileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='istasyon',
            name='akis_harita_emoji',
            field=models.CharField(blank=True, default='', help_text='Boşsa istasyon adına göre varsayılan emoji kullanılır. İleride görsel URL alanı eklenebilir.', max_length=16, verbose_name='Canlı akış ikonu'),
        ),
        migrations.AddField(
            model_name='istasyon',
            name='akis_harita_goster',
            field=models.BooleanField(default=True, verbose_name='Canlı akış haritasında göster'),
        ),
        migrations.AddField(
            model_name='istasyon',
            name='akis_harita_kisa_aciklama',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Canlı akış kısa açıklama'),
        ),
        migrations.AddField(
            model_name='istasyon',
            name='akis_tip_dis',
            field=models.BooleanField(default=False, help_text='Açık dış operasyon kayıtları bu istasyon sütununda listelenebilir (operasyon tipi ile eşleştirme).', verbose_name='Dış operasyon istasyonu'),
        ),
        migrations.AddField(
            model_name='operasyon',
            name='akis_dis_operasyon',
            field=models.BooleanField(default=False, help_text='İş emri bu adımdayken haritada dış operasyon (sarı/kırmızı) mantığı uygulanır.', verbose_name='Canlı akışta dış operasyon'),
        ),
    ]
