# Generated by Django 5.2.7 on 2026-05-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0108_canli_akis_harita_alanlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='disoperasyon',
            name='recete_operasyon',
            field=models.ForeignKey(blank=True, help_text='Reçeteden otomatik oluşturulduysa bağlantı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dis_kayitlari', to='stokapp.receteoperasyon', verbose_name='Reçete operasyon adımı'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_beklenen_donus_gun',
            field=models.PositiveSmallIntegerField(default=7, help_text='Beklenen dönüş tarihi = gönderim + bu gün (gönderim, işi başlattığınız gündür).', verbose_name='Beklenen dönüş (gün)'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_birim_fiyat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Dış operasyon birim fiyatı'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_gonderim_deposu',
            field=models.ForeignKey(blank=True, help_text='İsteğe bağlı; boşsa hareket deposu boş kaydedilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recete_dis_gonderimleri', to='stokapp.depo', verbose_name='Dış operasyon gönderim deposu'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_operasyon_tipi',
            field=models.ForeignKey(blank=True, help_text='İş emrinde bu adımda “İşi Başlat” ile otomatik dış operasyon oluşturulur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recete_operasyonlar', to='stokapp.disoperasyontipi', verbose_name='Dış operasyon tipi'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_para_birimi',
            field=models.CharField(choices=[('TL', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TL', max_length=3, verbose_name='Dış operasyon para birimi'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_sevk_evrak_no',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Sevk evrak / irsaliye no (isteğe bağlı)'),
        ),
        migrations.AddField(
            model_name='receteoperasyon',
            name='dis_tedarikci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recete_dis_operasyon_adimlari', to='stokapp.tedarikci', verbose_name='Dış operasyon taşeronu'),
        ),
    ]
