# Generated by Django 5.2.7 on 2026-05-19 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0109_recete_dis_operasyon_sablonu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='Adım anlık görüntüsü')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Ölçülen değer')),
                ('measured_unit', models.CharField(blank=True, choices=[('mm', 'mm'), ('cm', 'cm'), ('metre', 'metre'), ('adet', 'adet'), ('derece', 'derece'), ('kg', 'kg'), ('gr', 'gr'), ('N', 'N'), ('Nm', 'Nm'), ('bar', 'bar'), ('mikron', 'mikron'), ('diger', 'diğer')], max_length=20)),
                ('deviation', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('OK', 'Uygun'), ('NOK', 'Uygun Değil'), ('MISSING', 'Eksik ölçüm'), ('OUT_OF_REVISION', 'Revizyon dışı')], default='PENDING', max_length=20)),
                ('measurement_note', models.TextField(blank=True, verbose_name='Ölçüm notu')),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('sample_index', models.PositiveIntegerField(default=1, help_text='İleride tekrar ölçüm için örnek indeksi.', verbose_name='Örnek no')),
            ],
            options={
                'verbose_name': 'Kontrol ölçüm sonucu',
                'verbose_name_plural': 'Kontrol ölçüm sonuçları',
                'ordering': ['step__sort_order', 'step__step_no', 'sample_index'],
            },
        ),
        migrations.CreateModel(
            name='ProductionControlPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.CharField(default='R00', max_length=10, verbose_name='Revizyon no')),
                ('description', models.TextField(blank=True, verbose_name='Genel açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arşivlenme')),
                ('photo_annotation_schema', models.JSONField(blank=True, default=dict, help_text='İleride ok/daire/çizgi için altyapı.', verbose_name='Fotoğraf işaretleme şeması (ileride)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturdugu_uretim_kontrol_planlari', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_planlari', to='stokapp.stokitem', verbose_name='Ürün')),
                ('sub_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_alt_parca_planlari', to='stokapp.stokitem', verbose_name='Alt parça')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onceki_revizyonlar', to='stokapp.productioncontrolplan', verbose_name='Yerini alan plan')),
            ],
            options={
                'verbose_name': 'Üretim Kontrol Planı',
                'verbose_name_plural': 'Üretim Kontrol Planları',
                'ordering': ['product', 'sub_part', '-revision_no'],
                'unique_together': {('product', 'sub_part', 'revision_no')},
            },
        ),
        migrations.CreateModel(
            name='ProductionControlResultChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(blank=True, max_length=50)),
                ('new_value', models.CharField(blank=True, max_length=50)),
                ('change_note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='stokapp.productioncontrolresult')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionControlRevisionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_revision_no', models.CharField(max_length=10, verbose_name='Eski revizyon')),
                ('new_revision_no', models.CharField(max_length=10, verbose_name='Yeni revizyon')),
                ('change_note', models.TextField(verbose_name='Değişiklik açıklaması')),
                ('archived_data_json', models.JSONField(default=dict, verbose_name='Arşiv verisi')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_archives', to='stokapp.productioncontrolplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_archives', to='stokapp.productioncontrolplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_revizyon_urun', to='stokapp.stokitem', verbose_name='Ürün')),
                ('sub_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_revizyon_alt_parca', to='stokapp.stokitem', verbose_name='Alt parça')),
            ],
            options={
                'verbose_name': 'Kontrol planı revizyon arşivi',
                'verbose_name_plural': 'Kontrol planı revizyon arşivleri',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionControlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_plan_revision_no', models.CharField(max_length=10, verbose_name='Plan revizyon no')),
                ('control_date', models.DateField(verbose_name='Kontrol tarihi')),
                ('lot_no', models.CharField(blank=True, max_length=80, verbose_name='Parti / lot no')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Kontrol miktarı')),
                ('general_note', models.TextField(blank=True, verbose_name='Genel not')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('IN_PROGRESS', 'Devam ediyor'), ('PAUSED', 'Duraklatıldı'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=20)),
                ('final_result', models.CharField(blank=True, choices=[('', 'Belirlenmedi'), ('KABUL', 'Kabul'), ('RED', 'Red'), ('SARTLI', 'Şartlı Kabul')], default='', max_length=10)),
                ('current_step_index', models.PositiveIntegerField(default=0, verbose_name='Güncel adım indeksi')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='stokapp.productioncontrolplan', verbose_name='Kontrol planı')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yaptigi_uretim_kontrolleri', to=settings.AUTH_USER_MODEL, verbose_name='Kontrolcü')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_kontrol_oturumlari', to='stokapp.siparis')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_oturumlari', to='stokapp.stokitem')),
                ('sub_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uretim_kontrol_oturum_alt_parca', to='stokapp.stokitem')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_kontrol_oturumlari', to='stokapp.uretimemri')),
            ],
            options={
                'verbose_name': 'Üretim kontrol oturumu',
                'verbose_name_plural': 'Üretim kontrol oturumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productioncontrolresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='stokapp.productioncontrolsession', verbose_name='Oturum'),
        ),
        migrations.CreateModel(
            name='ProductionControlStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='Adım no')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uretim_kontrol/steps/%Y/%m/', verbose_name='Kontrol fotoğrafı')),
                ('photo_annotation_json', models.JSONField(blank=True, default=dict, verbose_name='Fotoğraf üzeri işaretleme (ileride)')),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Nominal değer')),
                ('nominal_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('metre', 'metre'), ('adet', 'adet'), ('derece', 'derece'), ('kg', 'kg'), ('gr', 'gr'), ('N', 'N'), ('Nm', 'Nm'), ('bar', 'bar'), ('mikron', 'mikron'), ('diger', 'diğer')], default='mm', max_length=20, verbose_name='Nominal birim')),
                ('plus_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Artı tolerans')),
                ('plus_tolerance_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('metre', 'metre'), ('adet', 'adet'), ('derece', 'derece'), ('kg', 'kg'), ('gr', 'gr'), ('N', 'N'), ('Nm', 'Nm'), ('bar', 'bar'), ('mikron', 'mikron'), ('diger', 'diğer')], default='mm', max_length=20, verbose_name='Artı tolerans birimi')),
                ('minus_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Eksi tolerans')),
                ('minus_tolerance_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('metre', 'metre'), ('adet', 'adet'), ('derece', 'derece'), ('kg', 'kg'), ('gr', 'gr'), ('N', 'N'), ('Nm', 'Nm'), ('bar', 'bar'), ('mikron', 'mikron'), ('diger', 'diğer')], default='mm', max_length=20, verbose_name='Eksi tolerans birimi')),
                ('measurement_method', models.CharField(choices=[('kumpas', 'Kumpas'), ('mikrometre', 'Mikrometre'), ('mihengir', 'Mihengir'), ('komparator', 'Komparatör'), ('serit_metre', 'Şerit metre'), ('gozle', 'Gözle kontrol'), ('diger', 'Diğer')], default='kumpas', max_length=50, verbose_name='Ölçüm yöntemi')),
                ('measurement_method_other', models.CharField(blank=True, max_length=120, verbose_name='Diğer yöntem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu kontrol')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Kritik ölçü')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('control_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='stokapp.productioncontrolplan', verbose_name='Kontrol planı')),
            ],
            options={
                'verbose_name': 'Kontrol adımı',
                'verbose_name_plural': 'Kontrol adımları',
                'ordering': ['sort_order', 'step_no', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productioncontrolresult',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_results', to='stokapp.productioncontrolstep', verbose_name='Adım'),
        ),
        migrations.AlterUniqueTogether(
            name='productioncontrolresult',
            unique_together={('session', 'step', 'sample_index')},
        ),
    ]
