# Generated by Django 5.2.7 on 2026-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0116_teklif_kismi_onay_siparis_kalemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayarlar',
            name='firma_logo',
            field=models.ImageField(blank=True, upload_to='firma_logo/', verbose_name='Firma Logosu'),
        ),
    ]
