# Generated by Django 5.2.7 on 2026-05-23 20:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _effective_machine_type(istasyon):
    raw = (getattr(istasyon, 'cnc_makine_grubu', None) or '').strip()
    if raw in ('cnc_lathe', 'cnc_mill'):
        return raw
    ad = (getattr(istasyon, 'ad', None) or '').lower()
    ad_norm = ad.replace('ı', 'i').replace('İ', 'i')
    if 'freze' in ad_norm or 'mill' in ad_norm:
        return 'cnc_mill'
    if 'torna' in ad_norm:
        return 'cnc_lathe'
    return ''


def _make_unique_slug(Makina, base_slug):
    slug = base_slug or 'makina'
    i = 2
    while Makina.objects.filter(slug=slug).exists():
        slug = f'{base_slug}-{i}' if base_slug else f'makina-{i}'
        i += 1
    return slug


def _ensure_fallback_makina(Istasyon, Makina, machine_type):
    if machine_type == 'cnc_lathe':
        base_name = 'CNC Torna Varsayılan'
    else:
        base_name = 'CNC Freze Varsayılan'

    ad = base_name
    i = 2
    while Istasyon.objects.filter(ad=ad).exists():
        ad = f'{base_name} {i}'
        i += 1

    istasyon = Istasyon.objects.create(
        ad=ad,
        aktif=False,
        sira=9999,
        cnc_makine_grubu=machine_type,
    )
    slug = _make_unique_slug(Makina, slugify(ad) or machine_type)
    return Makina.objects.create(
        istasyon=istasyon,
        slug=slug,
        sira=9999,
        aktif=True,
    )


def forwards_migrate_makina_data(apps, schema_editor):
    Istasyon = apps.get_model('stokapp', 'Istasyon')
    Makina = apps.get_model('stokapp', 'CncDosyaAgaciMakina')
    Klasor = apps.get_model('stokapp', 'CncDosyaAgaciKlasor')

    valid_types = {'cnc_lathe', 'cnc_mill'}

    # Aktif CNC istasyonlarından makina tanımı üret.
    for istasyon in Istasyon.objects.filter(aktif=True).order_by('sira', 'ad', 'id'):
        machine_type = _effective_machine_type(istasyon)
        if machine_type not in valid_types:
            continue
        if Makina.objects.filter(istasyon_id=istasyon.id).exists():
            continue
        slug = _make_unique_slug(Makina, slugify(istasyon.ad) or f'makina-{istasyon.id}')
        Makina.objects.create(
            istasyon_id=istasyon.id,
            slug=slug,
            sira=getattr(istasyon, 'sira', 0) or 0,
            aktif=True,
        )

    # Her tip için en az bir makina garanti et.
    by_type = {}
    for makina in Makina.objects.select_related('istasyon').order_by('sira', 'id'):
        machine_type = _effective_machine_type(makina.istasyon)
        if machine_type in valid_types and machine_type not in by_type:
            by_type[machine_type] = makina

    for machine_type in ('cnc_lathe', 'cnc_mill'):
        if machine_type not in by_type:
            by_type[machine_type] = _ensure_fallback_makina(Istasyon, Makina, machine_type)

    # Eski klasör kayıtlarını machine_type'a göre makina ile eşleştir.
    for machine_type, makina in by_type.items():
        Klasor.objects.filter(makina__isnull=True, machine_type=machine_type).update(makina_id=makina.id)

    # Her ihtimale karşı boşta kalanları torna fallback'ına bağla.
    fallback = by_type.get('cnc_lathe') or next(iter(by_type.values()), None)
    if fallback:
        Klasor.objects.filter(makina__isnull=True).update(makina_id=fallback.id)


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0117_genel_ayarlar_firma_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CncDosyaAgaciMakina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('istasyon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnc_dosya_agaci_makina', to='stokapp.istasyon', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'CNC Dosya Ağacı Makinası',
                'verbose_name_plural': 'CNC Dosya Ağacı Makinaları',
                'ordering': ['sira', 'istasyon__ad'],
            },
        ),
        migrations.AddField(
            model_name='cncdosyaagaciklasor',
            name='makina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klasorler', to='stokapp.cncdosyaagacimakina', verbose_name='Makina'),
        ),
        migrations.RunPython(forwards_migrate_makina_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cncdosyaagaciklasor',
            name='makina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasorler', to='stokapp.cncdosyaagacimakina', verbose_name='Makina'),
        ),
        migrations.RemoveIndex(
            model_name='cncdosyaagaciklasor',
            name='stokapp_cnc_machine_5affce_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cncdosyaagaciklasor',
            unique_together={('parent', 'name', 'makina')},
        ),
        migrations.AddIndex(
            model_name='cncdosyaagaciklasor',
            index=models.Index(fields=['makina', 'parent'], name='stokapp_cnc_makina__f7bdde_idx'),
        ),
        migrations.RemoveField(
            model_name='cncdosyaagaciklasor',
            name='machine_type',
        ),
    ]
