# Generated by Django 5.2.7 on 2026-06-03 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0120_genelayarlar_mail_cc_adresleri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimDegisiklikKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degisiklik_tipi', models.CharField(max_length=120, verbose_name='Değişiklik Tipi')),
                ('baslik', models.CharField(max_length=220, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('teknik_resim_guncellenecek', models.BooleanField(default=False, verbose_name='Teknik resim güncellenecek')),
                ('kati_model_guncellenecek', models.BooleanField(default=False, verbose_name='Katı model güncellenecek')),
                ('tekos_recete_guncellenecek', models.BooleanField(default=False, verbose_name='Tekos reçetesi güncellenecek')),
                ('ek_not', models.TextField(blank=True, verbose_name='Ek not')),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='ACIK', max_length=16, verbose_name='Durum')),
                ('oncelik', models.CharField(choices=[('DUSUK', 'Düşük'), ('ORTA', 'Orta'), ('YUKSEK', 'Yüksek'), ('KRITIK', 'Kritik')], default='ORTA', max_length=12, verbose_name='Öncelik')),
                ('termin_tarihi', models.DateField(blank=True, null=True, verbose_name='Termin')),
                ('kapatma_notu', models.TextField(blank=True, verbose_name='Kapatma notu')),
                ('kapatilan_tarih', models.DateTimeField(blank=True, null=True, verbose_name='Kapatılma tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kapatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kapatilan_uretim_degisim_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturulan_uretim_degisim_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uretim_degisim_kayitlari', to='stokapp.stokitem', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Üretim Değişiklik Kaydı',
                'verbose_name_plural': 'Üretim Değişiklik Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
