# Generated by Django 5.2.7 on 2026-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0121_uretimdegisiklikkaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uretimdegisiklikkaydi',
            name='cnc_programi_guncellenecek',
            field=models.BooleanField(default=False, verbose_name='CNC programı güncellenecek'),
        ),
    ]
