# Generated by Django 5.2.7 on 2026-06-06 10:10

from django.db import migrations, models


def urun_rolu_backfill(apps, schema_editor):
    StokItem = apps.get_model('stokapp', 'StokItem')
    StokItem.objects.filter(urun_tipi='URETIM').update(urun_rolu='NIHAI_URUN')
    StokItem.objects.exclude(urun_tipi='URETIM').update(urun_rolu='AL_SAT')


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0122_uretimdegisiklikkaydi_cnc_programi_guncellenecek'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokitem',
            name='urun_rolu',
            field=models.CharField(choices=[('AL_SAT', 'Al - Sat Ürün'), ('BILESEN', 'Üretim Bileşeni'), ('NIHAI_URUN', 'Nihai Ürün')], default='AL_SAT', max_length=20, verbose_name='Ürün Rolü'),
        ),
        migrations.RunPython(urun_rolu_backfill, migrations.RunPython.noop),
    ]
