# Generated by Django 5.2.7 on 2026-06-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0123_stokitem_urun_rolu'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalma',
            name='kaynak_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_satinalmalar', to='stokapp.siparis', verbose_name='Kaynak Sipariş'),
        ),
        migrations.AddField(
            model_name='tekliftalebi',
            name='kaynak_siparis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_rfqlar', to='stokapp.siparis', verbose_name='Kaynak Sipariş'),
        ),
    ]
