# Generated by Django 5.2.7 on 2026-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0131_aracbelgeturu_bitis_gerekmez'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayarlar',
            name='default_from_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Gönderen (From)'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='email_backend',
            field=models.CharField(choices=[('stokapp.email_backend.CustomSMTPEmailBackend', 'SMTP (Özel SSL — önerilen)'), ('django.core.mail.backends.smtp.EmailBackend', 'SMTP (Django varsayılan)'), ('django.core.mail.backends.console.EmailBackend', 'Konsol (test)'), ('django.core.mail.backends.filebased.EmailBackend', 'Dosyaya yaz (test)')], default='stokapp.email_backend.CustomSMTPEmailBackend', max_length=120, verbose_name='Giden posta backend'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='email_subject_prefix',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Konu öneki'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_body_max_chars',
            field=models.PositiveIntegerField(default=524288, verbose_name='IMAP gövde max karakter'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_hesaplari',
            field=models.JSONField(blank=True, default=list, help_text='[{"email": "...", "password": "..."}] formatında hesap listesi.', verbose_name='IMAP hesapları'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_mailbox',
            field=models.CharField(blank=True, default='INBOX', max_length=100, verbose_name='IMAP klasör'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_port',
            field=models.PositiveIntegerField(default=993, verbose_name='IMAP port'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_server',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='IMAP sunucu'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='IMAP SSL'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='pop_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='POP şifre'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='pop_port',
            field=models.PositiveIntegerField(default=995, verbose_name='POP port'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='pop_server',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='POP sunucu'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='pop_use_ssl',
            field=models.BooleanField(default=True, verbose_name='POP SSL'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='pop_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='POP kullanıcı'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='server_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Sunucu e-postası'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP sunucu'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP şifre'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SMTP zaman aşımı (sn)'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='SMTP SSL'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP STARTTLS'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP kullanıcı'),
        ),
    ]
