# Generated by Django 5.2.7 on 2026-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0133_stoksayimi_durum_hazir'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayarlar',
            name='fatura_adresi',
            field=models.TextField(blank=True, default='', help_text='Satınalma sipariş formunda fatura adresi olarak kullanılır.', verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='teslimat_adresi',
            field=models.TextField(blank=True, default='', help_text='Satınalma sipariş formunda teslimat adresi olarak kullanılır.', verbose_name='Teslimat Adresi'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='vergi_dairesi',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='genelayarlar',
            name='vergi_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Vergi Numarası'),
        ),
    ]
