# Generated by Django 5.2.7 on 2026-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokapp', '0134_genelayarlar_fatura_adresi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, help_text='Müşterinin ilgilendiği ürün/hizmet etiketleri. Teklif ve segmentasyon için kullanılır.', related_name='musteriler', to='stokapp.kategori', verbose_name='Etiketler / Kategoriler'),
        ),
    ]
